/* ---------------------------------------------------------------
   Bloom — content bank
   Placement test (40 Qs) + leveled Grammar & Punctuation lessons
----------------------------------------------------------------*/

const LEVEL_NAMES = {
  1: "Foundations",
  2: "Developing",
  3: "Proficient",
  4: "Advanced",
  5: "Expert"
};

const LEVEL_BLURB = {
  1: "You're building the essential rules — subject-verb agreement, apostrophes, and clear sentences.",
  2: "You're sharpening the everyday tricky spots — commas, semicolons, and word mix-ups.",
  3: "You're refining nuance — who/whom, subjunctive mood, and precise punctuation.",
  4: "You're polishing advanced style — idiom, concision, and formal register.",
  5: "You're mastering expert-level nuance — diction, layered punctuation, and elegant structure."
};

const CATEGORY_NAMES = {
  error: "Grammar & Sentence Errors",
  blank: "Word Choice",
  vocab: "Vocabulary",
  reading: "Reading Comprehension"
};

/* =================== PLACEMENT TEST (40 questions) =================== */
const PLACEMENT_QUESTIONS = [
  // ---- Error identification (12) ----
  { id:"pe1", type:"error", category:"error", sub:"Subject-Verb Agreement",
    prompt:"The committee members, each of whom ⟦bring⟧ years of experience, will review the proposal tomorrow.",
    options:["NO CHANGE","brings","has brought","bringing"], correctIndex:1,
    explanation:"\"Each\" is singular, so it needs the singular verb \"brings,\" even though \"members\" is plural." },
  { id:"pe2", type:"error", category:"error", sub:"Subject-Verb Agreement",
    prompt:"Neither the manager nor the employees ⟦was⟧ aware of the new policy.",
    options:["NO CHANGE","were","is","being"], correctIndex:1,
    explanation:"With \"neither...nor,\" the verb agrees with the closer subject — the plural \"employees\" — so it should be \"were.\"" },
  { id:"pe3", type:"error", category:"error", sub:"Dangling Modifiers",
    prompt:"Walking briskly through the park, ⟦the sudden rainstorm caught Maria off guard⟧.",
    options:["NO CHANGE","Maria was caught off guard by the sudden rainstorm","the sudden rainstorm, catching Maria off guard","Maria, caught off guard, the sudden rainstorm"], correctIndex:1,
    explanation:"The opening phrase describes who was walking, so the subject right after the comma must be the walker — Maria, not the rainstorm." },
  { id:"pe4", type:"error", category:"error", sub:"Verb Tense",
    prompt:"By the time we arrived, the movie ⟦already started⟧.",
    options:["NO CHANGE","had already started","has already started","already starts"], correctIndex:1,
    explanation:"For an action completed before another past action, use the past perfect: \"had already started.\"" },
  { id:"pe5", type:"error", category:"error", sub:"Apostrophes",
    prompt:"⟦Its⟧ important to proofread your essay before submitting it.",
    options:["NO CHANGE","It's","Its'","Their"], correctIndex:1,
    explanation:"\"It's\" is the contraction for \"it is,\" which is what the sentence means here. \"Its\" is possessive." },
  { id:"pe6", type:"error", category:"error", sub:"Concision",
    prompt:"The reason she was late ⟦is because⟧ her car broke down.",
    options:["NO CHANGE","is that","was because","being that"], correctIndex:1,
    explanation:"\"The reason is because\" is redundant. \"The reason...is that\" is the standard, concise construction." },
  { id:"pe7", type:"error", category:"error", sub:"Pronoun Case",
    prompt:"⟦Me and him⟧ went to the store yesterday.",
    options:["NO CHANGE","He and I","Him and me","I and he"], correctIndex:1,
    explanation:"As the subject of the sentence, the pronouns need the subjective case: \"He and I,\" with the speaker named last." },
  { id:"pe8", type:"error", category:"error", sub:"Subject-Verb Agreement",
    prompt:"Each of the students ⟦have⟧ completed their assignment.",
    options:["NO CHANGE","has","having","had"], correctIndex:1,
    explanation:"\"Each\" is singular, so it takes the singular verb \"has,\" regardless of the plural noun in \"of the students.\"" },
  { id:"pe9", type:"error", category:"error", sub:"Pronoun Case",
    prompt:"The teacher gave the award to ⟦whomever⟧ scored the highest.",
    options:["NO CHANGE","whoever","who","which"], correctIndex:1,
    explanation:"The pronoun is the subject of \"scored,\" so it needs the subjective form \"whoever,\" not the objective \"whomever.\"" },
  { id:"pe10", type:"error", category:"error", sub:"Pronoun Case",
    prompt:"Between you and ⟦I⟧, this project is going to fail.",
    options:["NO CHANGE","me","myself","mine"], correctIndex:1,
    explanation:"\"Between\" is a preposition, and prepositions take the objective case: \"between you and me.\"" },
  { id:"pe11", type:"error", category:"error", sub:"Dangling Modifiers",
    prompt:"After finishing the marathon, ⟦a hot shower was all Jake wanted⟧.",
    options:["NO CHANGE","Jake wanted nothing more than a hot shower","a hot shower, which Jake wanted, was ready","wanting a hot shower, Jake"], correctIndex:1,
    explanation:"The opening phrase describes Jake, the one who finished the marathon, so \"Jake\" must follow the comma as the subject." },
  { id:"pe12", type:"error", category:"error", sub:"Subject-Verb Agreement",
    prompt:"The data suggests that the new policy ⟦are⟧ effective.",
    options:["NO CHANGE","is effective","being effective","were effective"], correctIndex:1,
    explanation:"The verb here agrees with the singular subject \"policy,\" not \"data,\" so it should be \"is effective.\"" },

  // ---- Fill in the blank (10) ----
  { id:"pb1", type:"blank", category:"blank", sub:"Word Choice",
    prompt:"Despite her _____ efforts to remain calm, she couldn't hide her excitement.",
    options:["valiant","vacant","vagrant","valid"], correctIndex:0,
    explanation:"\"Valiant\" (brave, determined) fits an effort to stay composed under pressure." },
  { id:"pb2", type:"blank", category:"blank", sub:"Word Choice",
    prompt:"The professor's lecture was so _____ that several students fell asleep.",
    options:["riveting","tedious","concise","eloquent"], correctIndex:1,
    explanation:"Students falling asleep signals a boring lecture — \"tedious\" fits, while the other options describe engaging or brief talks." },
  { id:"pb3", type:"blank", category:"blank", sub:"Word Choice",
    prompt:"The two proposals are virtually _____; choosing between them will be difficult.",
    options:["identical","contradictory","obsolete","arbitrary"], correctIndex:0,
    explanation:"Difficulty choosing between two things suggests they're very similar — \"identical\" fits best." },
  { id:"pb4", type:"blank", category:"blank", sub:"Word Choice",
    prompt:"Because the evidence was purely _____, the jury could not reach a verdict.",
    options:["circumstantial","conclusive","irrefutable","documented"], correctIndex:0,
    explanation:"Evidence that fails to produce a verdict is weak or indirect — \"circumstantial\" — not conclusive or irrefutable." },
  { id:"pb5", type:"blank", category:"blank", sub:"Word Choice",
    prompt:"The new manager's _____ approach alienated employees who valued open discussion.",
    options:["collaborative","authoritarian","diplomatic","amiable"], correctIndex:1,
    explanation:"Alienating employees who want open discussion points to a controlling, top-down style — \"authoritarian.\"" },
  { id:"pb6", type:"blank", category:"blank", sub:"Word Choice",
    prompt:"Her _____ remarks during the meeting offended several colleagues.",
    options:["tactless","gracious","measured","benevolent"], correctIndex:0,
    explanation:"Remarks that offend people are insensitive — \"tactless\" is the fit; the others describe kind or careful speech." },
  { id:"pb7", type:"blank", category:"blank", sub:"Word Choice",
    prompt:"Although early results were promising, the scientist's hypothesis was later _____ when new data contradicted it.",
    options:["corroborated","disproven","theoretical","anecdotal"], correctIndex:1,
    explanation:"\"Contradicted\" is the key clue — data that contradicts a hypothesis disproves it." },
  { id:"pb8", type:"blank", category:"blank", sub:"Word Choice",
    prompt:"The company's profits have grown at a _____ pace over the last decade, far outstripping its competitors.",
    options:["sluggish","meteoric","modest","stagnant"], correctIndex:1,
    explanation:"\"Far outstripping its competitors\" signals rapid, dramatic growth — \"meteoric.\"" },
  { id:"pb9", type:"blank", category:"blank", sub:"Word Choice",
    prompt:"Even the most _____ critics praised the film's stunning cinematography.",
    options:["skeptical","adoring","lenient","uncritical"], correctIndex:0,
    explanation:"\"Even the most...\" signals a contrast — hard-to-please, \"skeptical\" critics still praised it." },
  { id:"pb10", type:"blank", category:"blank", sub:"Word Choice",
    prompt:"The negotiations reached an _____ after both sides refused to compromise.",
    options:["impasse","accord","agreement","resolution"], correctIndex:0,
    explanation:"Refusing to compromise leads to a deadlock — an \"impasse\" — not an agreement." },

  // ---- Vocabulary in context (8) ----
  { id:"pv1", type:"vocab", category:"vocab", sub:"Vocabulary",
    prompt:"The senator's speech was criticized for being unnecessarily verbose. As used here, \"verbose\" most nearly means:",
    options:["wordy","persuasive","offensive","brief"], correctIndex:0,
    explanation:"\"Verbose\" means using far more words than needed." },
  { id:"pv2", type:"vocab", category:"vocab", sub:"Vocabulary",
    prompt:"The old house had an air of dilapidation that suggested years of neglect. As used here, \"dilapidation\" most nearly means:",
    options:["elegance","disrepair","mystery","grandeur"], correctIndex:1,
    explanation:"\"Dilapidation\" describes a state of disrepair or decay, matching \"years of neglect.\"" },
  { id:"pv3", type:"vocab", category:"vocab", sub:"Vocabulary",
    prompt:"Her candid response surprised the interviewer, who expected a more guarded answer. As used here, \"candid\" most nearly means:",
    options:["honest","hostile","rehearsed","nervous"], correctIndex:0,
    explanation:"\"Candid\" means open and honest, contrasting with the \"guarded\" answer the interviewer expected." },
  { id:"pv4", type:"vocab", category:"vocab", sub:"Vocabulary",
    prompt:"The company's opaque accounting practices raised concerns among investors. As used here, \"opaque\" most nearly means:",
    options:["unclear","illegal","efficient","outdated"], correctIndex:0,
    explanation:"\"Opaque\" literally means not transparent; here it means the practices were hard to understand or see through." },
  { id:"pv5", type:"vocab", category:"vocab", sub:"Vocabulary",
    prompt:"He remained stoic throughout the difficult surgery, showing no sign of pain. As used here, \"stoic\" most nearly means:",
    options:["emotionally unaffected","deeply distressed","physically weak","overly dramatic"], correctIndex:0,
    explanation:"\"Stoic\" describes someone who endures hardship without showing emotion, matching \"showing no sign of pain.\"" },
  { id:"pv6", type:"vocab", category:"vocab", sub:"Vocabulary",
    prompt:"The critic's scathing review devastated the young playwright. As used here, \"scathing\" most nearly means:",
    options:["harshly critical","mildly positive","balanced","confusing"], correctIndex:0,
    explanation:"A review that \"devastated\" someone was severely, harshly critical." },
  { id:"pv7", type:"vocab", category:"vocab", sub:"Vocabulary",
    prompt:"The professor's terse email left no room for further discussion. As used here, \"terse\" most nearly means:",
    options:["brief and curt","warm and lengthy","apologetic","ambiguous"], correctIndex:0,
    explanation:"\"Terse\" means using few words, often abruptly — fitting an email that shut down discussion." },
  { id:"pv8", type:"vocab", category:"vocab", sub:"Vocabulary",
    prompt:"The volatile stock market made investors increasingly anxious. As used here, \"volatile\" most nearly means:",
    options:["unpredictable","stable","profitable","declining"], correctIndex:0,
    explanation:"\"Volatile\" means prone to sudden, unpredictable change — the cause of investor anxiety." },

  // ---- Reading comprehension (10, across 3 passages) ----
  { id:"pr1", type:"reading", category:"reading", sub:"Reading Comprehension", passageId:"A",
    passage:"Honeybees are often celebrated for their honey, but their most vital contribution to agriculture is pollination. As a bee forages for nectar, pollen grains cling to the fine hairs covering its body. When the bee visits the next flower, some of this pollen brushes off, fertilizing the plant. This process, though invisible to most observers, sustains roughly a third of the food crops humans consume, from almonds to apples. In recent decades, however, bee populations have declined sharply due to habitat loss, pesticide exposure, and a parasitic mite known as Varroa destructor. Scientists warn that without intervention, this decline could threaten food security worldwide. Some farmers have responded by planting wildflower buffers around their fields, providing bees with diverse forage and a healthier habitat.",
    prompt:"According to the passage, pollination primarily occurs when:",
    options:["bees intentionally carry pollen to help farmers","pollen grains stick to a bee's body and transfer between flowers","bees produce pollen inside their bodies","farmers manually pollinate crops"], correctIndex:1,
    explanation:"The passage describes pollen clinging to a bee's hairs and brushing off onto the next flower it visits." },
  { id:"pr2", type:"reading", category:"reading", sub:"Reading Comprehension", passageId:"A",
    prompt:"The passage suggests that wildflower buffers are intended to:",
    options:["replace the need for bees entirely","provide bees with better habitat and food sources","eliminate the Varroa mite","increase honey production for sale"], correctIndex:1,
    explanation:"The passage states farmers plant these buffers to give bees \"diverse forage and a healthier habitat.\"" },
  { id:"pr3", type:"reading", category:"reading", sub:"Reading Comprehension", passageId:"A",
    prompt:"Which best describes the author's tone toward declining bee populations?",
    options:["dismissive","alarmed but solution-oriented","indifferent","celebratory"], correctIndex:1,
    explanation:"The passage raises a serious warning (\"could threaten food security\") but also highlights a proactive response, reflecting concern paired with hope." },
  { id:"pr4", type:"reading", category:"reading", sub:"Reading Comprehension", passageId:"B",
    passage:"Every morning of my childhood began the same way: a two-mile walk to school along a gravel road that wound past my grandfather's orchard. In autumn, the apples hung so heavy that their weight bent the branches toward the ground, and I would pick one on my way past, biting into it before I'd gone another ten steps. My grandfather always waved from the porch, though I rarely saw him leave it. It wasn't until years later, when I returned to find the orchard sold and the road paved over, that I understood how much of my sense of home had been built on those small, repeated moments — the crunch of gravel, the sweetness of a stolen apple, a hand raised in greeting.",
    prompt:"The narrator's understanding of \"home\" is best described as:",
    options:["tied to a specific building she lived in","built gradually through small, repeated experiences","something she never fully understood","based mainly on family conversations"], correctIndex:1,
    explanation:"The final sentence attributes her sense of home to \"small, repeated moments,\" not a building or conversation." },
  { id:"pr5", type:"reading", category:"reading", sub:"Reading Comprehension", passageId:"B",
    prompt:"The phrase \"a stolen apple\" most likely suggests that the narrator:",
    options:["felt genuine guilt about taking apples","took the apples without asking, in a playful, harmless way","was punished for taking the apples","disliked the taste of the apples"], correctIndex:1,
    explanation:"The warm, nostalgic tone of the passage frames the apple-taking as an innocent childhood habit, not a real theft." },
  { id:"pr6", type:"reading", category:"reading", sub:"Reading Comprehension", passageId:"B",
    prompt:"The final sentence primarily serves to:",
    options:["describe the orchard's current condition","list the specific details that gave the narrator's childhood its meaning","criticize the changes to the road","explain why the narrator moved away"], correctIndex:1,
    explanation:"The sentence catalogs sensory details (\"crunch of gravel,\" \"sweetness of a stolen apple\") that defined her sense of home." },
  { id:"pr7", type:"reading", category:"reading", sub:"Reading Comprehension", passageId:"C",
    passage:"Urban planners have increasingly turned their attention to green space — parks, tree-lined streets, community gardens — as a tool for improving city life. The benefits extend well beyond aesthetics. Studies have linked access to green space with lower rates of stress-related illness, improved air quality, and even reduced crime in some neighborhoods. Yet green space is not distributed equally. Wealthier neighborhoods often boast expansive parks and mature tree canopies, while lower-income areas frequently contend with vacant lots and minimal shade. This disparity, sometimes called the 'green gap,' has prompted several cities to adopt policies requiring new developments to include public green space, regardless of a neighborhood's income level. Critics argue that such policies can raise property values and inadvertently accelerate the displacement of longtime residents, a phenomenon known as green gentrification. Balancing environmental equity with housing affordability remains an unresolved challenge.",
    prompt:"According to the passage, green space has been linked to all of the following EXCEPT:",
    options:["lower stress-related illness","improved air quality","reduced crime","increased population density"], correctIndex:3,
    explanation:"The passage names lower stress-related illness, improved air quality, and reduced crime as benefits — population density is never mentioned." },
  { id:"pr8", type:"reading", category:"reading", sub:"Reading Comprehension", passageId:"C",
    prompt:"The term \"green gap\" refers to:",
    options:["the physical distance between parks in a city","the unequal distribution of green space across neighborhoods of different incomes","a shortage of tree species in urban areas","the difference between real and artificial grass"], correctIndex:1,
    explanation:"The passage defines the term right after describing wealthier neighborhoods having more green space than lower-income ones." },
  { id:"pr9", type:"reading", category:"reading", sub:"Reading Comprehension", passageId:"C",
    prompt:"\"Green gentrification\" as described in the passage is problematic because it:",
    options:["reduces the number of parks in a city","can drive up property values and displace longtime residents","makes green spaces less environmentally friendly","discourages cities from building parks at all"], correctIndex:1,
    explanation:"The passage states critics worry the policies \"raise property values and inadvertently accelerate the displacement of longtime residents.\"" },
  { id:"pr10", type:"reading", category:"reading", sub:"Reading Comprehension", passageId:"C",
    prompt:"The overall structure of the passage moves from:",
    options:["a proposed solution to a description of its failure","a general benefit to a specific inequity and its complications","a historical account to a prediction about the future","a personal anecdote to a broad generalization"], correctIndex:1,
    explanation:"The passage opens with the general benefits of green space, then narrows to the inequity (\"green gap\") and its complications (\"green gentrification\")." }
];

/* =================== GRAMMAR & PUNCTUATION LESSON BANK =================== */
/* type: "error" (NO CHANGE style) or "blank" (choose the correct word) */
const GRAMMAR_BANK = [
  /* ---------------- LEVEL 1 — Foundations ---------------- */
  { id:"g1-1", level:1, type:"error", sub:"Subject-Verb Agreement",
    prompt:"The dog ⟦run⟧ across the yard every morning.",
    options:["NO CHANGE","runs","running","ran"], correctIndex:1,
    explanation:"The singular subject \"dog\" needs the singular verb \"runs.\"" },
  { id:"g1-2", level:1, type:"error", sub:"Apostrophes",
    prompt:"The cat licked ⟦it's⟧ paw before curling up to sleep.",
    options:["NO CHANGE","its","its'","it is"], correctIndex:1,
    explanation:"The possessive form of \"it\" has no apostrophe: \"its.\" \"It's\" always means \"it is\" or \"it has.\"" },
  { id:"g1-3", level:1, type:"error", sub:"Comma Usage",
    prompt:"For breakfast I had ⟦eggs toast and orange juice⟧.",
    options:["NO CHANGE","eggs, toast, and orange juice","eggs toast, and orange juice","eggs, toast and, orange juice"], correctIndex:1,
    explanation:"Items in a series need commas between each item, including before \"and\" (the Oxford comma)." },
  { id:"g1-4", level:1, type:"error", sub:"Run-ons & Fragments",
    prompt:"⟦I love reading books, I read every night before bed.⟧",
    options:["NO CHANGE","I love reading books; I read every night before bed.","I love reading books I read every night before bed.","I love reading books, and, I read every night before bed."], correctIndex:1,
    explanation:"Two independent clauses can't be joined with just a comma (a comma splice). A semicolon correctly links them." },
  { id:"g1-5", level:1, type:"error", sub:"Capitalization",
    prompt:"Last summer we visited ⟦paris and rome⟧.",
    options:["NO CHANGE","Paris and Rome","Paris and rome","paris and Rome"], correctIndex:1,
    explanation:"City names are proper nouns and must always be capitalized." },
  { id:"g1-6", level:1, type:"error", sub:"Pronoun Case",
    prompt:"⟦Her and me⟧ went to the movies on Friday.",
    options:["NO CHANGE","She and I","Her and I","She and me"], correctIndex:1,
    explanation:"As the subject of the sentence, both pronouns need the subjective case: \"She and I.\"" },
  { id:"g1-7", level:1, type:"blank", sub:"Word Usage",
    prompt:"I can't believe _____ finally here after months of planning.",
    options:["they're","their","there","them're"], correctIndex:0,
    explanation:"\"They're\" is the contraction for \"they are,\" which fits the sentence." },
  { id:"g1-8", level:1, type:"error", sub:"End Punctuation",
    prompt:"Did you finish your homework⟦.⟧",
    options:["NO CHANGE","?","!",";"], correctIndex:1,
    explanation:"This sentence asks a question, so it must end with a question mark." },
  { id:"g1-9", level:1, type:"error", sub:"Subject-Verb Agreement",
    prompt:"The boxes of books ⟦was⟧ heavy to carry.",
    options:["NO CHANGE","were","is","being"], correctIndex:1,
    explanation:"The subject is the plural \"boxes,\" not \"books\"; \"of books\" is just a prepositional phrase, so the verb should be \"were.\"" },
  { id:"g1-10", level:1, type:"error", sub:"Apostrophes",
    prompt:"The ⟦childrens⟧ toys were scattered across the floor.",
    options:["NO CHANGE","children's","childrens'","childrens's"], correctIndex:1,
    explanation:"\"Children\" is already plural, so its possessive form simply adds 's: \"children's.\"" },
  { id:"g1-11", level:1, type:"error", sub:"Comma Usage",
    prompt:"I wanted to go to the party ⟦but I had too much homework⟧.",
    options:["NO CHANGE",", but I had too much homework.","but, I had too much homework.","but I had, too much homework."], correctIndex:1,
    explanation:"When \"but\" joins two independent clauses, a comma belongs before it." },
  { id:"g1-12", level:1, type:"blank", sub:"Word Usage",
    prompt:"Please put the book over _____ on the shelf.",
    options:["there","their","they're","theyre"], correctIndex:0,
    explanation:"\"There\" refers to a place, which fits this sentence." },
  { id:"g1-13", level:1, type:"error", sub:"Run-ons & Fragments",
    prompt:"⟦Because I was tired.⟧",
    options:["NO CHANGE","Because I was tired, I went to bed early.","I was tired because.","Tired, because I was."], correctIndex:1,
    explanation:"\"Because I was tired\" is a fragment — it needs an independent clause attached to form a complete sentence." },
  { id:"g1-14", level:1, type:"error", sub:"Pronoun Agreement",
    prompt:"A student wants to succeed, so ⟦you⟧ must study every night.",
    options:["NO CHANGE","they","it","have"], correctIndex:1,
    explanation:"The sentence starts in third person (\"a student\") and shouldn't shift to second person (\"you\"); \"they\" keeps it consistent." },
  { id:"g1-15", level:1, type:"blank", sub:"Word Usage",
    prompt:"_____ going to the beach this weekend if the weather is nice.",
    options:["We're","Were","Where","Wear"], correctIndex:0,
    explanation:"\"We're\" is the contraction for \"we are,\" which fits at the start of this sentence." },

  /* ---------------- LEVEL 2 — Developing ---------------- */
  { id:"g2-1", level:2, type:"error", sub:"Comma Usage",
    prompt:"⟦After the long meeting everyone was exhausted.⟧",
    options:["NO CHANGE","After the long meeting, everyone was exhausted.","After, the long meeting everyone was exhausted.","After the long, meeting everyone was exhausted."], correctIndex:1,
    explanation:"A comma follows an introductory phrase to separate it from the main clause." },
  { id:"g2-2", level:2, type:"blank", sub:"Word Usage",
    prompt:"The new policy will _____ how employees schedule their vacation time.",
    options:["affect","effect","affects","effected"], correctIndex:0,
    explanation:"\"Affect\" is almost always the verb meaning \"to influence.\" \"Effect\" is usually the noun (a result)." },
  { id:"g2-3", level:2, type:"error", sub:"Apostrophes",
    prompt:"The two ⟦companies⟧ profits were merged after the acquisition.",
    options:["NO CHANGE","companies'","company's","companies's"], correctIndex:1,
    explanation:"\"Companies\" is already plural, so the possessive just adds an apostrophe: \"companies'.\"" },
  { id:"g2-4", level:2, type:"error", sub:"Subject-Verb Agreement",
    prompt:"The team ⟦are⟧ celebrating their victory tonight.",
    options:["NO CHANGE","is","were","being"], correctIndex:1,
    explanation:"In American English, collective nouns like \"team\" typically take a singular verb when acting as one unit." },
  { id:"g2-5", level:2, type:"error", sub:"Pronoun Agreement",
    prompt:"The company announced that ⟦they will release their⟧ earnings report next week.",
    options:["NO CHANGE","it will release its","it will release their","they will release its"], correctIndex:1,
    explanation:"\"Company\" is a singular noun, so it should be referred to with the singular pronouns \"it\" and \"its.\"" },
  { id:"g2-6", level:2, type:"error", sub:"Semicolons & Colons",
    prompt:"I wanted to visit the museum, ⟦however, it⟧ was closed for renovations.",
    options:["NO CHANGE","; however, it","however, it,","however it,"], correctIndex:1,
    explanation:"When \"however\" joins two independent clauses, it needs a semicolon before it and a comma after it." },
  { id:"g2-7", level:2, type:"blank", sub:"Word Usage",
    prompt:"This year's harvest was much larger _____ last year's.",
    options:["then","than","that","them"], correctIndex:1,
    explanation:"\"Than\" is used for comparisons; \"then\" refers to time or sequence." },
  { id:"g2-8", level:2, type:"error", sub:"Misplaced Modifiers",
    prompt:"⟦The waiter served pancakes to the customers covered in syrup.⟧",
    options:["NO CHANGE","The waiter served the customers pancakes covered in syrup.","Covered in syrup, the waiter served pancakes to the customers.","The waiter, covered in syrup, served pancakes to the customers."], correctIndex:1,
    explanation:"As written, it sounds like the customers are covered in syrup. Moving the modifier next to \"pancakes\" fixes the confusion." },
  { id:"g2-9", level:2, type:"error", sub:"Parallel Structure",
    prompt:"She enjoys hiking, swimming, and ⟦to ride her bike⟧.",
    options:["NO CHANGE","riding her bike","she rides her bike","ridden her bike"], correctIndex:1,
    explanation:"To match \"hiking\" and \"swimming,\" the third item needs the same -ing form: \"riding.\"" },
  { id:"g2-10", level:2, type:"error", sub:"Comma Usage",
    prompt:"⟦My sister who lives in Chicago is visiting next week.⟧",
    options:["NO CHANGE","My sister, who lives in Chicago, is visiting next week.","My sister, who lives in Chicago is visiting next week.","My sister who lives in Chicago, is visiting next week."], correctIndex:1,
    explanation:"If you have only one sister, \"who lives in Chicago\" adds extra, nonessential information and needs commas on both sides." },
  { id:"g2-11", level:2, type:"error", sub:"Subject-Verb Agreement",
    prompt:"Neither of the answers ⟦seem⟧ correct to me.",
    options:["NO CHANGE","seems","is seeming","seeming"], correctIndex:1,
    explanation:"\"Neither\" is singular, so it takes the singular verb \"seems.\"" },
  { id:"g2-12", level:2, type:"blank", sub:"Word Usage",
    prompt:"The company decided to _____ new safety regulations after the accident.",
    options:["implement","imply","infer","impede"], correctIndex:0,
    explanation:"\"Implement\" means to put into effect, which fits new regulations being adopted." },
  { id:"g2-13", level:2, type:"error", sub:"Apostrophes",
    prompt:"The ⟦1990's⟧ were known for grunge music and early internet culture.",
    options:["NO CHANGE","1990s","1990s'","1990,s"], correctIndex:1,
    explanation:"Decades are made plural without an apostrophe: \"1990s.\"" },
  { id:"g2-14", level:2, type:"error", sub:"Parallel Structure",
    prompt:"The instructions were clear, concise, and ⟦written well⟧.",
    options:["NO CHANGE","well-written","writing well","to be well written"], correctIndex:1,
    explanation:"To match the single-word adjectives \"clear\" and \"concise,\" the third item should be the adjective \"well-written.\"" },
  { id:"g2-15", level:2, type:"error", sub:"Run-ons & Fragments",
    prompt:"⟦The rain didn't stop all day, we still went hiking.⟧",
    options:["NO CHANGE","The rain didn't stop all day, but we still went hiking.","The rain didn't stop all day we still went hiking.","The rain didn't stop all day, so, we still went hiking."], correctIndex:1,
    explanation:"A comma alone can't join two independent clauses; adding \"but\" after the comma fixes the splice and shows contrast." },

  /* ---------------- LEVEL 3 — Proficient ---------------- */
  { id:"g3-1", level:3, type:"error", sub:"Pronoun Case",
    prompt:"⟦Who⟧ did you give the report to?",
    options:["NO CHANGE","Whom","Whoever","Whomever"], correctIndex:1,
    explanation:"The pronoun is the object of the preposition \"to,\" so it needs the objective case: \"whom.\"" },
  { id:"g3-2", level:3, type:"blank", sub:"Word Usage",
    prompt:"There were _____ people at the concert than we expected.",
    options:["fewer","less","lesser","few"], correctIndex:0,
    explanation:"\"Fewer\" is used for countable nouns like \"people.\" \"Less\" is for uncountable quantities." },
  { id:"g3-3", level:3, type:"error", sub:"Semicolons & Colons",
    prompt:"She had one goal this year⟦, to run a marathon⟧.",
    options:["NO CHANGE",": to run a marathon.","; to run a marathon.","— to, run a marathon."], correctIndex:1,
    explanation:"A colon introduces an explanation or elaboration after a complete independent clause." },
  { id:"g3-4", level:3, type:"error", sub:"Dangling Modifiers",
    prompt:"⟦Having studied all night, the exam felt manageable to Sarah.⟧",
    options:["NO CHANGE","Having studied all night, Sarah found the exam manageable.","The exam, having studied all night, felt manageable to Sarah.","Studying all night, it felt manageable to Sarah."], correctIndex:1,
    explanation:"\"Having studied all night\" describes Sarah, so \"Sarah\" must be the subject right after the comma." },
  { id:"g3-5", level:3, type:"blank", sub:"Word Usage",
    prompt:"From your tone, I _____ that you're upset with me.",
    options:["infer","imply","inferring","implication"], correctIndex:0,
    explanation:"\"Infer\" means to draw a conclusion from evidence — what the listener does. \"Imply\" is what the speaker does." },
  { id:"g3-6", level:3, type:"error", sub:"Apostrophes",
    prompt:"⟦Mike and Sarahs'⟧ project won first place at the science fair.",
    options:["NO CHANGE","Mike and Sarah's","Mike's and Sarah's","Mikes and Sarahs"], correctIndex:1,
    explanation:"For joint ownership of one project, only the last name takes the possessive: \"Mike and Sarah's.\"" },
  { id:"g3-7", level:3, type:"error", sub:"Parallel Structure",
    prompt:"She not only enjoys painting but also ⟦to write poetry⟧.",
    options:["NO CHANGE","writing poetry","write poetry","wrote poetry"], correctIndex:1,
    explanation:"\"Not only...but also\" requires matching grammatical forms on both sides: \"enjoys painting\" and \"writing poetry.\"" },
  { id:"g3-8", level:3, type:"error", sub:"That vs. Which",
    prompt:"The laptop, ⟦that I bought last year⟧, already needs repairs.",
    options:["NO CHANGE","which I bought last year","that, I bought, last year","whom I bought last year"], correctIndex:1,
    explanation:"Nonrestrictive clauses (set off by commas, adding extra info) use \"which,\" not \"that.\"" },
  { id:"g3-9", level:3, type:"blank", sub:"Word Usage",
    prompt:"We need to discuss this issue _____ before making a decision.",
    options:["further","farther","farthest","furthest"], correctIndex:0,
    explanation:"\"Further\" is used for figurative or abstract extent, while \"farther\" refers to physical distance." },
  { id:"g3-10", level:3, type:"error", sub:"Subjunctive Mood",
    prompt:"If I ⟦was⟧ you, I would accept the job offer.",
    options:["NO CHANGE","were","am","had been"], correctIndex:1,
    explanation:"Hypothetical, contrary-to-fact statements use the subjunctive \"were,\" even with a singular subject like \"I.\"" },
  { id:"g3-11", level:3, type:"error", sub:"Semicolons & Colons",
    prompt:"The team visited three cities: ⟦Paris, France, Rome, Italy, and Berlin, Germany⟧.",
    options:["NO CHANGE","Paris, France; Rome, Italy; and Berlin, Germany","Paris; France, Rome; Italy, and Berlin; Germany","Paris France, Rome Italy, and Berlin Germany"], correctIndex:1,
    explanation:"When list items already contain commas, semicolons separate the items to avoid confusion." },
  { id:"g3-12", level:3, type:"error", sub:"Comparative Forms",
    prompt:"Of the two candidates, she is clearly the ⟦most qualified⟧.",
    options:["NO CHANGE","more qualified","much qualified","qualifiedest"], correctIndex:1,
    explanation:"When comparing exactly two things, use the comparative form (\"more qualified\"), not the superlative." },
  { id:"g3-13", level:3, type:"blank", sub:"Word Usage",
    prompt:"The medication had a noticeable _____ on his mood.",
    options:["effect","affect","effecting","affecting"], correctIndex:0,
    explanation:"\"Effect\" is the noun meaning \"a result,\" which fits after \"a noticeable.\"" },
  { id:"g3-14", level:3, type:"error", sub:"Parallel Structure",
    prompt:"The report outlines the problem, proposes solutions, and ⟦it recommended⟧ a timeline.",
    options:["NO CHANGE","recommends","recommending","will recommend"], correctIndex:1,
    explanation:"To stay parallel with \"outlines\" and \"proposes,\" the third verb should also be present tense: \"recommends.\"" },
  { id:"g3-15", level:3, type:"error", sub:"Pronoun Case",
    prompt:"The candidate ⟦whom⟧ we believe will win the election spoke at the rally.",
    options:["NO CHANGE","who","whoever","which"], correctIndex:1,
    explanation:"\"Who\" is the subject of \"will win\"; \"we believe\" is just a parenthetical insertion, so it doesn't change the pronoun's case." },

  /* ---------------- LEVEL 4 — Advanced ---------------- */
  { id:"g4-1", level:4, type:"error", sub:"Ambiguous Pronouns",
    prompt:"⟦When Emma told her sister about the promotion, she was thrilled.⟧",
    options:["NO CHANGE","When Emma told her sister about the promotion, her sister was thrilled.","When Emma told her sister about the promotion, she, her sister, was thrilled.","She told her sister about the promotion, and she was thrilled."], correctIndex:1,
    explanation:"\"She\" could refer to Emma or her sister. Naming \"her sister\" directly removes the ambiguity." },
  { id:"g4-2", level:4, type:"blank", sub:"Word Usage",
    prompt:"The chef received a lovely _____ on his soufflé from a food critic.",
    options:["compliment","complement","complimentary","complements"], correctIndex:0,
    explanation:"A \"compliment\" is praise. A \"complement\" is something that completes or pairs well with something else." },
  { id:"g4-3", level:4, type:"blank", sub:"Word Usage",
    prompt:"The results of this study are different _____ those of previous research.",
    options:["from","than","to","with"], correctIndex:0,
    explanation:"\"Different from\" is the standard idiom in formal English." },
  { id:"g4-4", level:4, type:"error", sub:"Concision",
    prompt:"⟦In my personal opinion, I think that⟧ the plan is likely to succeed.",
    options:["NO CHANGE","In my opinion,","In my personal opinion, I personally think that","It is my opinion that I think"], correctIndex:1,
    explanation:"\"In my personal opinion, I think that\" repeats the same idea three times. \"In my opinion\" says it once, clearly." },
  { id:"g4-5", level:4, type:"blank", sub:"Word Usage",
    prompt:"Honesty is a core _____ that guides her decisions.",
    options:["principle","principal","principled","principally"], correctIndex:0,
    explanation:"A \"principle\" is a fundamental belief or rule. A \"principal\" is a person in charge or a main/primary thing." },
  { id:"g4-6", level:4, type:"error", sub:"Comma Usage",
    prompt:"⟦My favorite author Toni Morrison wrote Beloved in 1987.⟧",
    options:["NO CHANGE","My favorite author, Toni Morrison, wrote Beloved in 1987.","My favorite author, Toni Morrison wrote Beloved in 1987.","My favorite author Toni Morrison, wrote Beloved in 1987."], correctIndex:1,
    explanation:"\"Toni Morrison\" renames \"my favorite author\" as extra, nonessential information, so it needs commas on both sides." },
  { id:"g4-7", level:4, type:"error", sub:"Subjunctive Mood",
    prompt:"The committee recommended that he ⟦submits⟧ his application by Friday.",
    options:["NO CHANGE","submit","submitted","will submit"], correctIndex:1,
    explanation:"After verbs like \"recommend\" that express a demand or suggestion, use the subjunctive base form: \"submit.\"" },
  { id:"g4-8", level:4, type:"blank", sub:"Word Usage",
    prompt:"The detective hoped the interview would _____ new information about the case.",
    options:["elicit","illicit","elicited","illicitly"], correctIndex:0,
    explanation:"\"Elicit\" means to draw out. \"Illicit\" means illegal or forbidden." },
  { id:"g4-9", level:4, type:"error", sub:"Clarity & Structure",
    prompt:"⟦The manual explains clearly and in detail how to, without causing damage, replace the filter.⟧",
    options:["NO CHANGE","The manual explains clearly and in detail how to replace the filter without causing damage.","The manual explains how to replace, clearly and in detail, the filter without causing damage.","Clearly and in detail, without causing damage, the manual explains how to replace the filter."], correctIndex:1,
    explanation:"Keeping \"how to replace the filter\" together, with the modifier at the end, reads far more naturally than interrupting the phrase." },
  { id:"g4-10", level:4, type:"blank", sub:"Word Usage",
    prompt:"With the storm's arrival _____, residents were urged to evacuate.",
    options:["imminent","eminent","immanent","ambient"], correctIndex:0,
    explanation:"\"Imminent\" means about to happen. \"Eminent\" means distinguished or famous." },
  { id:"g4-11", level:4, type:"error", sub:"Parallel Structure",
    prompt:"The CEO's strategy focused on reducing costs, improving morale, and ⟦to expand into new markets⟧.",
    options:["NO CHANGE","expanding into new markets","expansion into new markets","that would expand into new markets"], correctIndex:1,
    explanation:"To match the -ing forms \"reducing\" and \"improving,\" the third item should be \"expanding.\"" },
  { id:"g4-12", level:4, type:"blank", sub:"Word Usage",
    prompt:"The professor's theory is based _____ decades of research.",
    options:["on","in","from","by"], correctIndex:0,
    explanation:"\"Based on\" is the standard idiomatic pairing in English." },
  { id:"g4-13", level:4, type:"blank", sub:"Word Usage",
    prompt:"The company reported a smaller _____ of complaints this quarter.",
    options:["number","amount","quantity of","less"], correctIndex:0,
    explanation:"\"Number\" is used for countable nouns like \"complaints.\" \"Amount\" is for uncountable quantities." },
  { id:"g4-14", level:4, type:"error", sub:"Comma Usage",
    prompt:"Students who study consistently⟦,⟧ tend to perform better on exams.",
    options:["NO CHANGE","(no comma)","tend, to perform better","tend to, perform better"], correctIndex:1,
    explanation:"\"Who study consistently\" is essential to identifying which students — it's a restrictive clause and shouldn't be set off by a comma." },
  { id:"g4-15", level:4, type:"blank", sub:"Word Usage",
    prompt:"Please _____ that the doors are locked before you leave.",
    options:["ensure","assure","insure","ensuring"], correctIndex:0,
    explanation:"\"Ensure\" means to make certain. \"Assure\" means to tell someone confidently; \"insure\" means to protect financially." },

  /* ---------------- LEVEL 5 — Expert ---------------- */
  { id:"g5-1", level:5, type:"error", sub:"Semicolons & Colons",
    prompt:"The recipe requires⟦:⟧ flour, sugar, butter, and eggs.",
    options:["NO CHANGE","(no punctuation)",";",",  and"], correctIndex:1,
    explanation:"A colon must follow a complete independent clause — it can't sit directly after a verb like \"requires.\"" },
  { id:"g5-2", level:5, type:"blank", sub:"Word Usage",
    prompt:"The data was organized into five _____ categories.",
    options:["discrete","discreet","discretely","discreetly"], correctIndex:0,
    explanation:"\"Discrete\" means separate and distinct. \"Discreet\" means careful or tactful." },
  { id:"g5-3", level:5, type:"blank", sub:"Word Usage",
    prompt:"The celebrity was criticized for _____ her wealth at the charity gala.",
    options:["flaunting","flouting","flaunted","flout"], correctIndex:0,
    explanation:"\"Flaunt\" means to show off. \"Flout\" means to openly disregard a rule." },
  { id:"g5-4", level:5, type:"blank", sub:"Word Usage",
    prompt:"As a judge, she remained entirely _____ in the outcome, favoring neither side.",
    options:["disinterested","uninterested","interested","disinteresting"], correctIndex:0,
    explanation:"\"Disinterested\" means impartial, which fits a judge favoring neither side. \"Uninterested\" means not caring at all." },
  { id:"g5-5", level:5, type:"error", sub:"Subjunctive Mood",
    prompt:"If the treaty ⟦would have been signed⟧ earlier, the conflict might have been avoided.",
    options:["NO CHANGE","had been signed","was signed","would be signed"], correctIndex:1,
    explanation:"The \"if\" clause of a counterfactual takes the past perfect (\"had been signed\"), not \"would have.\"" },
  { id:"g5-6", level:5, type:"error", sub:"Parallel Structure",
    prompt:"The policy not only failed to reduce emissions but also ⟦it increased⟧ costs for consumers.",
    options:["NO CHANGE","increased","was increasing","also, it was increasing"], correctIndex:1,
    explanation:"\"Not only...but also\" should join two matching verb phrases: \"failed to reduce\" and \"increased,\" without repeating the subject." },
  { id:"g5-7", level:5, type:"error", sub:"Pronoun Case",
    prompt:"The scholarship will be awarded to ⟦whoever⟧ the committee selects.",
    options:["NO CHANGE","whomever","who","which"], correctIndex:1,
    explanation:"The pronoun is the object of \"selects\" (the committee selects whom), so it needs the objective form \"whomever.\"" },
  { id:"g5-8", level:5, type:"blank", sub:"Word Usage",
    prompt:"The museum houses artifacts from various _____ periods.",
    options:["historical","historic","history's","historically"], correctIndex:0,
    explanation:"\"Historical\" means relating to history in general. \"Historic\" means significant in history." },
  { id:"g5-9", level:5, type:"error", sub:"Formal Register",
    prompt:"⟦I literally died laughing⟧ when I heard the joke.",
    options:["NO CHANGE","I could hardly stop laughing","I almost literally died laughing","I figuratively died laughing"], correctIndex:1,
    explanation:"In formal writing, \"literally\" shouldn't be used to mean its opposite (figuratively); a direct description reads more precisely." },
  { id:"g5-10", level:5, type:"error", sub:"Comma Usage",
    prompt:"My colleague, whose research focuses on climate policy⟦ recently⟧ published a book.",
    options:["NO CHANGE",", recently","; recently","— recently"], correctIndex:1,
    explanation:"The nonrestrictive clause \"whose research focuses on climate policy\" needs a closing comma to match its opening comma." },
  { id:"g5-11", level:5, type:"error", sub:"Semicolons & Colons",
    prompt:"⟦There are three requirements for the grant, a completed application, two letters of recommendation, and a research proposal, late submissions will not be considered.⟧",
    options:["NO CHANGE","There are three requirements for the grant: a completed application, two letters of recommendation, and a research proposal; late submissions will not be considered.","There are three requirements for the grant; a completed application, two letters of recommendation, and a research proposal, late submissions will not be considered.","There are three requirements for the grant, a completed application, two letters of recommendation, and a research proposal; late submissions will not be considered."], correctIndex:1,
    explanation:"A colon should introduce the list after the independent clause, and a semicolon should separate the following independent clause about late submissions." },
  { id:"g5-12", level:5, type:"error", sub:"Pronoun Case",
    prompt:"The award goes to the researcher ⟦who⟧ the committee, after months of deliberation, decided to honor.",
    options:["NO CHANGE","whom","whoever","which"], correctIndex:1,
    explanation:"The pronoun is the object of \"decided to honor\"; the parenthetical \"after months of deliberation\" doesn't change that it needs the objective case \"whom.\"" },
  { id:"g5-13", level:5, type:"blank", sub:"Word Usage",
    prompt:"The _____ scholar was invited to deliver the keynote address.",
    options:["eminent","imminent","immanent","ambient"], correctIndex:0,
    explanation:"\"Eminent\" means distinguished or well-known, which fits a scholar being invited to speak." },
  { id:"g5-14", level:5, type:"error", sub:"Dangling Modifiers",
    prompt:"⟦Having reviewed all the evidence, a guilty verdict was reached by the jury.⟧",
    options:["NO CHANGE","Having reviewed all the evidence, the jury reached a guilty verdict.","A guilty verdict, having reviewed all the evidence, was reached.","The evidence led the jury to a guilty verdict."], correctIndex:1,
    explanation:"\"Having reviewed all the evidence\" describes the jury, so \"the jury\" must be the subject right after the comma." },
  { id:"g5-15", level:5, type:"blank", sub:"Word Usage",
    prompt:"The recipe takes _____ than twenty minutes to prepare.",
    options:["less","fewer","lesser","few"], correctIndex:0,
    explanation:"When referring to a single span of time as one quantity, \"less\" is correct, even though \"minutes\" looks countable." }
];
