/* ---------------------------------------------------------------
   Bloom — content bank
   Placement test (40 Qs) + leveled Grammar & Punctuation lessons
----------------------------------------------------------------*/

const LEVEL_NAMES = {
  1: "Foundations",
  2: "Developing",
  3: "Proficient",
  4: "Advanced",
  5: "Expert"
};

const LEVEL_BLURB = {
  1: "You're building the essential rules — subject-verb agreement, apostrophes, and clear sentences.",
  2: "You're sharpening the everyday tricky spots — commas, semicolons, and word mix-ups.",
  3: "You're refining nuance — who/whom, subjunctive mood, and precise punctuation.",
  4: "You're polishing advanced style — idiom, concision, and formal register.",
  5: "You're mastering expert-level nuance — diction, layered punctuation, and elegant structure."
};

const CATEGORY_NAMES = {
  error: "Grammar & Sentence Errors",
  blank: "Word Choice",
  vocab: "Vocabulary",
  reading: "Reading Comprehension"
};

/* =================== PLACEMENT TEST POOL =================== */
const PLACEMENT_POOL = [
  // ---- Error identification (12) ----
  { id:"pe1", type:"error", category:"error", sub:"Sequence of Tense",
    prompt:"The analyst reported that the company's earnings ⟦had exceeded⟧ forecasts every quarter since the policy took effect, a trend that continues today.",
    options:["NO CHANGE","has exceeded","were exceeding","have exceeded"], correctIndex:3,
    explanation:"\"Continues today\" signals the trend is still ongoing, which calls for the present perfect \"have exceeded,\" not the past perfect \"had exceeded\" (which would imply it stopped). \"Has exceeded\" is a tempting near-miss — it gets the tense right but wrongly treats the plural \"earnings\" as singular." },
  { id:"pe2", type:"error", category:"error", sub:"Pronoun Case",
    prompt:"Our new marketing director has far more industry experience than ⟦him⟧, though he was hired for a fraction of the salary.",
    options:["NO CHANGE","himself","he was","he"], correctIndex:3,
    explanation:"This is an elliptical comparison: \"than he [has]\" — the pronoun is the implied subject of \"has,\" so it takes the subjective case \"he.\" \"Than him\" sounds natural in casual speech, which is exactly what makes it such a common error." },
  { id:"pe3", type:"error", category:"error", sub:"Subjunctive Mood",
    prompt:"He carried himself as if he ⟦was⟧ already the department's next director, though the decision hadn't been announced.",
    options:["NO CHANGE","is","had been","were"], correctIndex:3,
    explanation:"\"As if\" introducing a hypothetical, contrary-to-fact situation takes the subjunctive \"were.\" \"Had been\" is a tempting near-miss, but it wrongly implies a completed state before some past point rather than a present hypothetical." },
  { id:"pe4", type:"error", category:"error", sub:"Pronoun Case",
    prompt:"When the results were finally announced, everyone assumed it was ⟦her⟧ who had leaked the memo.",
    options:["NO CHANGE","hers","herself","she"], correctIndex:3,
    explanation:"After the linking verb \"was,\" formal grammar requires the subjective case \"she\" (a predicate nominative), even though \"it was her\" is extremely common in casual speech — one of the hardest rules to apply against instinct." },
  { id:"pe5", type:"error", category:"error", sub:"Parallel Structure",
    prompt:"⟦Not only was the report late, but it also⟧ contained several factual errors that had to be corrected before publication.",
    options:["NO CHANGE","Not only the report was late, but it also","Not only was the report late, but the report also","Not only was the report late, but also it"], correctIndex:0,
    explanation:"Fronting the negative \"not only\" correctly triggers subject-auxiliary inversion (\"was the report\"), and \"but it also\" is the standard follow-up — the sentence is already correct. \"Not only the report was late\" skips the required inversion, a genuine and common error; repeating \"the report\" instead of using \"it\" is grammatical but needlessly clunky." },
  { id:"pe6", type:"error", category:"error", sub:"Faulty Predication",
    prompt:"The reason the merger collapsed ⟦was due to⟧ regulators blocking it at the last minute.",
    options:["NO CHANGE","was caused by","is due to","was that"], correctIndex:3,
    explanation:"\"The reason...was due to\" redundantly combines two ways of stating cause. \"Was caused by\" is a tempting near-miss — it's grammatical, but it illogically implies the reason itself was caused by something, rather than being the cause." },
  { id:"pe7", type:"error", category:"error", sub:"Parallel Structure",
    prompt:"The new manager was both ⟦critical and responsible for⟧ several major decisions that quarter.",
    options:["NO CHANGE","critical about and responsible for","critical with and responsible for","critical of and responsible for"], correctIndex:3,
    explanation:"\"Critical\" needs its own preposition — \"of,\" not \"about\" or \"with\" — since it can't correctly share \"for\" with \"responsible.\"" },
  { id:"pe8", type:"error", category:"error", sub:"Dangling Modifiers",
    prompt:"⟦Its funding secured⟧, the museum's board unanimously approved the expansion, a decision reluctant donors had delayed for years.",
    options:["NO CHANGE","Having secured its funding","Securing its funding","With its funding, secured"], correctIndex:0,
    explanation:"\"Its funding secured\" is a nominative absolute — it has its own built-in subject (\"funding\") and doesn't need to logically match \"the museum's board,\" so it's already correct. \"Having secured its funding\" looks like a fix but actually creates a real dangling modifier, since it's now \"the museum,\" not \"the board,\" that grammatically did the securing." },
  { id:"pe9", type:"error", category:"error", sub:"Word Usage",
    prompt:"The advisory panel ⟦is comprised of⟧ five economists, three attorneys, and two former regulators.",
    options:["NO CHANGE","comprises of","is comprised by","comprises"], correctIndex:3,
    explanation:"\"Comprise\" already means \"to consist of\"; the whole comprises its parts. \"Comprises of\" is a very common hypercorrection — people fix \"is comprised of\" partway, but \"comprise\" is never followed by \"of.\"" },
  { id:"pe10", type:"error", category:"error", sub:"That vs. Which",
    prompt:"Employees who receive top performance ratings⟦, that⟧ are determined by a blind peer-review panel, qualify for the annual bonus pool.",
    options:["NO CHANGE","that","which",", which"], correctIndex:3,
    explanation:"This clause simply adds extra information about how ratings are determined — it isn't distinguishing among several kinds of \"top performance ratings\" — so it's nonrestrictive and needs both the comma and \"which.\" Dropping the comma (\"which\" alone) is a common punctuation lapse, since nonrestrictive \"which\" almost always wants one." },
  { id:"pe11", type:"error", category:"error", sub:"Subject-Verb Agreement",
    prompt:"Roughly forty percent of the survey's respondents ⟦was undecided⟧ about the proposed merger, according to preliminary results.",
    options:["NO CHANGE","is undecided","has been undecided","were undecided"], correctIndex:3,
    explanation:"With \"percent of,\" the verb agrees with the object of \"of\" — here, the plural \"respondents\" — so \"were\" is correct. \"Is undecided\" is a tempting near-miss since \"percent\" itself feels singular." },
  { id:"pe12", type:"error", category:"error", sub:"Parallel Structure",
    prompt:"The city council will either postpone the vote or ⟦it will schedule⟧ a special session before the deadline, depending on the committee's recommendation.",
    options:["NO CHANGE","it should schedule","would schedule","schedule"], correctIndex:3,
    explanation:"\"Either...or\" should join two matching verb phrases sharing \"will\": \"postpone\" and \"schedule.\" \"Would schedule\" breaks the parallel by switching to a different, inconsistent modal verb; \"it should schedule\" reintroduces the subject with yet another modal." },

  // ---- Fill in the blank (10) ----
  { id:"pb1", type:"blank", category:"blank", sub:"Word Usage",
    prompt:"By requiring collateral upfront, the lender sought to _____ the risk of default entirely, rather than merely reducing its impact.",
    options:["obviate","mitigate","alleviate","circumvent"], correctIndex:0,
    explanation:"\"Obviate\" means to eliminate a problem entirely, matching \"entirely\" and the explicit contrast with \"merely reducing its impact.\" \"Mitigate\" and \"alleviate\" both mean to lessen severity — exactly the weaker outcome the sentence rules out." },
  { id:"pb2", type:"blank", category:"blank", sub:"Word Usage",
    prompt:"The coalition's platform remained _____ well into the campaign, still evolving from a loose set of grievances toward what might eventually become a coherent policy agenda.",
    options:["inchoate","provisional","equivocal","ephemeral"], correctIndex:0,
    explanation:"\"Inchoate\" describes something just beginning to take shape, not yet fully formed — matching \"still evolving...toward.\" \"Provisional\" means temporary/subject to change (not necessarily unformed); \"equivocal\" describes unclear meaning, not undeveloped structure." },
  { id:"pb3", type:"blank", category:"blank", sub:"Word Usage",
    prompt:"The scandal's fallout proved _____ for the CEO, who resigned within a week despite having no direct role in the fraud.",
    options:["ruinous","onerous","invidious","specious"], correctIndex:0,
    explanation:"\"Ruinous\" means devastatingly destructive, matching a forced resignation. \"Onerous\" means burdensome (describing a difficult duty, not a destructive outcome); \"invidious\" means likely to provoke resentment; \"specious\" means superficially plausible but false." },
  { id:"pb4", type:"blank", category:"blank", sub:"Word Usage",
    prompt:"After the leaked emails surfaced, the board voted to formally _____ the executive, a public rebuke that stopped short of termination.",
    options:["censure","censor","admonish","recuse"], correctIndex:0,
    explanation:"\"Censure\" means to formally, officially rebuke — exactly what a board vote produces. \"Censor\" (to suppress content) is a classic spelling-based mix-up with an unrelated meaning." },
  { id:"pb5", type:"blank", category:"blank", sub:"Word Usage",
    prompt:"The candidate's evasive answer visibly _____ the moderator, who paused for a long moment before moving to the next question.",
    options:["discomfited","discomforted","disparaged","dissuaded"], correctIndex:0,
    explanation:"\"Discomfit\" means to fluster or throw into confusion — matching the long, uncertain pause. \"Discomforted\" (mere physical or mild unease) is a near-identical-looking word with a weaker, less precise fit." },
  { id:"pb6", type:"blank", category:"blank", sub:"Word Usage",
    prompt:"Out of respect for the grieving family, reporters agreed to _____ from asking about the crash's cause during the vigil.",
    options:["forbear","forebear","forswear","forestall"], correctIndex:0,
    explanation:"\"Forbear\" means to hold back or refrain. \"Forebear\" (an ancestor) is a noun with a completely different meaning and a classic spelling-based mix-up." },
  { id:"pb7", type:"blank", category:"blank", sub:"Word Usage",
    prompt:"Before the acquisition closed, an independent firm was hired to formally _____ the target company's real estate holdings.",
    options:["appraise","apprise","appropriate","arbitrate"], correctIndex:0,
    explanation:"\"Appraise\" means to assess the value of something. \"Apprise\" (to inform someone of something) is a near-identical spelling with an entirely different meaning — one of the most common mix-ups in business writing." },
  { id:"pb8", type:"blank", category:"blank", sub:"Word Usage",
    prompt:"Known for her _____ attention to procedural detail, the judge rejected the motion on a minor technicality that both attorneys had overlooked.",
    options:["punctilious","censorious","judicious","capricious"], correctIndex:0,
    explanation:"\"Punctilious\" means meticulously attentive to detail and formality. \"Judicious\" means showing sound judgment generally — close in flavor, but it describes wisdom, not fastidious attention to procedural minutiae." },
  { id:"pb9", type:"blank", category:"blank", sub:"Word Usage",
    prompt:"Despite the market's violent swings that week, the fund manager maintained a remarkable _____, neither panicking during the crash nor celebrating the rebound.",
    options:["equanimity","equivocation","complacency","equity"], correctIndex:0,
    explanation:"\"Equanimity\" means calm composure under pressure. \"Complacency\" is a tempting near-miss, but it implies unconcerned indifference — while the sentence shows the manager actively tracking both the crash and the rebound, just without losing composure." },
  { id:"pb10", type:"blank", category:"blank", sub:"Word Usage",
    prompt:"After a decade covering war zones, the photographer had grown _____ to scenes that once would have haunted her for weeks.",
    options:["inured","immune","impervious","indifferent"], correctIndex:0,
    explanation:"\"Inured\" specifically describes becoming desensitized through repeated exposure over time — matching \"after a decade.\" \"Immune\" usually implies innate protection rather than a gradual process; \"indifferent\" wrongly implies she never cared in the first place." },

  // ---- Vocabulary in context (8) ----
  { id:"pv1", type:"vocab", category:"vocab", sub:"Vocabulary",
    prompt:"Historians still debate whether the general's perfidious surrender to the enemy was a calculated betrayal or simple incompetence. As used here, \"perfidious\" most nearly means:",
    options:["treacherously disloyal","reluctantly forced","surprisingly swift","publicly humiliating"], correctIndex:0,
    explanation:"\"Perfidious\" means deliberately deceitful or treacherous — fitting the framing of \"betrayal.\" The other options describe circumstances of the surrender, not the disloyalty the word specifically names." },
  { id:"pv2", type:"vocab", category:"vocab", sub:"Vocabulary",
    prompt:"The junior associates' obsequious flattery of the managing partner embarrassed even those who also hoped for a promotion. As used here, \"obsequious\" most nearly means:",
    options:["excessively eager to please","genuinely sincere","quietly reserved","openly hostile"], correctIndex:0,
    explanation:"\"Obsequious\" describes fawning, excessive flattery meant to win favor — matching why it was embarrassing to watch. \"Genuinely sincere\" is a near-opposite that a careless reader might guess from the positive-sounding word \"flattery.\"" },
  { id:"pv3", type:"vocab", category:"vocab", sub:"Vocabulary",
    prompt:"Throughout the sentencing, the defendant remained impassive, betraying no emotion even as the victim's family spoke. As used here, \"impassive\" most nearly means:",
    options:["showing no emotion","overcome with emotion","visibly remorseful","quietly defiant"], correctIndex:0,
    explanation:"\"Impassive\" means expressionless, showing no feeling — confirmed by \"betraying no emotion.\" Its resemblance to \"passionate\" tempts some readers to guess the opposite meaning." },
  { id:"pv4", type:"vocab", category:"vocab", sub:"Vocabulary",
    prompt:"Economists warn that the pernicious effects of the subsidy may not become apparent for another decade, long after the policy's initial popularity fades. As used here, \"pernicious\" most nearly means:",
    options:["harmful in a gradual, subtle way","immediately obvious","financially profitable","widely publicized"], correctIndex:0,
    explanation:"\"Pernicious\" means harmful in a way that isn't immediately apparent. \"Immediately obvious\" directly contradicts \"may not become apparent for another decade\" — a trap for a reader who associates \"effects\" with visible, dramatic harm." },
  { id:"pv5", type:"vocab", category:"vocab", sub:"Vocabulary",
    prompt:"Despite three formal appeals and a personal visit from the ambassador, the minister remained obdurate, refusing even to discuss the sanctions. As used here, \"obdurate\" most nearly means:",
    options:["stubbornly unyielding","quietly uncertain","openly apologetic","carefully diplomatic"], correctIndex:0,
    explanation:"\"Obdurate\" means stubbornly resistant to persuasion — matching a minister who won't even discuss the issue despite repeated appeals." },
  { id:"pv6", type:"vocab", category:"vocab", sub:"Vocabulary",
    prompt:"The sommelier's supercilious tone made even confident diners second-guess their wine choices. As used here, \"supercilious\" most nearly means:",
    options:["arrogantly disdainful","warmly encouraging","nervously uncertain","technically precise"], correctIndex:0,
    explanation:"\"Supercilious\" describes haughty, condescending superiority — the kind of tone that would make diners doubt themselves. \"Technically precise\" is tempting given the wine-expert context, but it doesn't capture the attitude the word actually names." },
  { id:"pv7", type:"vocab", category:"vocab", sub:"Vocabulary",
    prompt:"Colleagues learned to gauge the CEO's mercurial moods before bringing him bad news, since his reaction on any given morning was impossible to predict. As used here, \"mercurial\" most nearly means:",
    options:["unpredictably changeable","quietly calculating","consistently harsh","highly intelligent"], correctIndex:0,
    explanation:"\"Mercurial\" means prone to sudden, unpredictable shifts in mood — confirmed by \"impossible to predict.\" \"Consistently harsh\" is a trap, since \"consistently\" directly contradicts the volatility the sentence describes; some readers also wrongly link the word to cleverness via its root, \"Mercury.\"" },
  { id:"pv8", type:"vocab", category:"vocab", sub:"Vocabulary",
    prompt:"The lawyer's specious argument sounded convincing at first, but it fell apart under closer examination. As used here, \"specious\" most nearly means:",
    options:["seemingly plausible but false","spacious and open","special and unique","clearly correct and well-supported"], correctIndex:0,
    explanation:"\"Specious\" describes something that appears true or reasonable but isn't — confirmed by \"fell apart under closer examination.\" Its resemblance to \"spacious\" and \"special\" causes frequent mix-ups." },

  // ---- Reading comprehension (10, across 3 shared passages) ----
  { id:"pr1", type:"reading", category:"reading", sub:"Reading Comprehension", passageId:"A",
    passage:"Over the past decade, researchers replicating landmark psychology studies have succeeded barely half the time, a pattern known as the reproducibility crisis. Some blame small sample sizes and selective reporting, where striking results get published while null findings go unseen. Others locate the problem deeper, in incentives that reward novelty over rigor. Whatever the cause, the result is the same: a body of accepted knowledge riddled with findings that may not hold up. Some journals now require researchers to register hypotheses before collecting data, curbing the temptation to reshape conclusions after seeing results.",
    prompt:"Which of the following, if true, would most directly undermine the passage's suggestion that incentive structures are a root cause of the reproducibility crisis?",
    options:["Other scientific fields with similarly novelty-driven incentive structures show significantly higher replication rates than psychology.","Psychology journals have begun requiring larger sample sizes for publication.","Researchers who pre-register their hypotheses report feeling less pressure to produce novel results.","The rate of replication failures has remained stable over the past decade."], correctIndex:0,
    explanation:"If other fields share the same incentive to reward novelty but don't share psychology's replication problem, that suggests incentives alone don't explain it. The other options either address a different candidate cause (sample size) or are consistent with — not contrary to — the incentive explanation." },
  { id:"pr2", type:"reading", category:"reading", sub:"Reading Comprehension", passageId:"A",
    prompt:"The passage's mention of pre-registration primarily functions to:",
    options:["illustrate one concrete response to the problem, without claiming it resolves the disagreement about causes","resolve the debate over whether sample size or incentive structures is the true cause","suggest that selective reporting is a more serious problem than small sample sizes","prove that the reproducibility crisis has already been solved in most fields"], correctIndex:0,
    explanation:"The passage presents pre-registration as a practice that curbs one specific temptation — it never claims to settle which underlying cause is more important, or that the crisis is resolved." },
  { id:"pr3", type:"reading", category:"reading", sub:"Reading Comprehension", passageId:"A",
    prompt:"Based on the passage, which assumption underlies the claim that selective reporting distorts \"a body of accepted knowledge\"?",
    options:["Published findings meaningfully influence what comes to be accepted as established knowledge","All published psychology findings are eventually proven false","Researchers deliberately choose which results to report based on personal bias","Null findings are always more accurate than striking findings"], correctIndex:0,
    explanation:"The claim only makes sense if what gets published actually shapes accepted knowledge. The passage attributes selective reporting to incentives and norms, not personal bias, and never claims all findings are false or that null results are inherently more accurate." },

  { id:"pr4", type:"reading", category:"reading", sub:"Reading Comprehension", passageId:"B",
    passage:"Every morning of my childhood began the same way: a walk along a gravel road past my grandfather's orchard. In autumn, the apples hung so heavy the branches bent toward the ground, and I'd pick one without slowing, biting into it before I'd gone another ten steps. My grandfather always waved from the porch, though I rarely saw him leave it. Only years later, returning to find the orchard sold and the road paved over, did I understand how much of my sense of home had rested on those small, repeated moments rather than on any single place.",
    prompt:"The passage's central claim about the nature of \"home\" is best supported by which detail?",
    options:["The narrator emphasizes ordinary sensory details rather than any single significant event","The narrator describes her grandfather's orchard in great botanical detail","The narrator explains exactly why the orchard was eventually sold","The narrator contrasts her adult neighborhood unfavorably with her childhood one"], correctIndex:0,
    explanation:"The passage builds its claim entirely from small, repeated sensory details — gravel, apples, a wave — not from any dramatic event. It never explains why the orchard was sold, and it draws no such contrast with her adult life." },
  { id:"pr5", type:"reading", category:"reading", sub:"Reading Comprehension", passageId:"B",
    prompt:"The narrator's tone in describing the walk to school is best characterized as:",
    options:["quietly nostalgic, finding meaning in retrospect she may not have consciously noticed at the time","openly resentful of how ordinary her childhood was","anxious about forgetting these memories as she grows older","proud of having recognized the importance of these moments even as a child"], correctIndex:0,
    explanation:"The passage explicitly says she \"understood\" the significance of these moments only \"years later\" — not as a child, which rules out the tempting but subtly wrong last option." },
  { id:"pr6", type:"reading", category:"reading", sub:"Reading Comprehension", passageId:"B",
    prompt:"Which addition to the passage would most directly reinforce its final claim about the sources of the narrator's sense of home?",
    options:["A description of an unremarkable routine from later in her life that also felt meaningful only in hindsight","A detailed history of when and why her grandfather first planted the orchard","An explanation of the exact price the orchard sold for","A comparison between this orchard and other, more famous orchards in the region"], correctIndex:0,
    explanation:"The passage's claim is about small, repeated moments building a sense of home — a second example of that same pattern would reinforce it directly. The other additions are historical or comparative details unrelated to that specific claim." },

  { id:"pr7", type:"reading", category:"reading", sub:"Reading Comprehension", passageId:"C",
    passage:"Urban planners increasingly treat green space — parks, tree-lined streets, community gardens — as more than an amenity. Studies link it to lower rates of stress-related illness, cleaner air, and even reduced crime. Yet the benefit is unevenly distributed: wealthier neighborhoods tend to have expansive parks and mature tree canopies, while lower-income areas often make do with vacant lots and little shade — a disparity sometimes called the 'green gap.' Several cities have responded by requiring new developments to include public green space regardless of income. Critics counter that such requirements raise nearby property values and can hasten the displacement of longtime residents, a pattern known as green gentrification.",
    prompt:"The passage's argument that green-space requirements can lead to green gentrification depends on which unstated assumption?",
    options:["Developers and buyers place a financial premium on proximity to green space, raising nearby housing costs","Cities enforce green-space requirements unevenly across neighborhoods","Lower-income residents are unaware that new parks are being built nearby","Green space requires significant ongoing maintenance funding"], correctIndex:0,
    explanation:"For new green space to raise property values and displace residents, it must be true that people pay more to live near it. The passage explicitly describes requirements applied \"regardless of income,\" ruling out uneven enforcement, and never suggests residents are uninformed." },
  { id:"pr8", type:"reading", category:"reading", sub:"Reading Comprehension", passageId:"C",
    prompt:"Which of the following would most directly weaken the critics' argument about green gentrification, as described in the passage?",
    options:["Property values near new public green space rise no faster than property values citywide","New parks reduce crime rates in the surrounding blocks","Most new developments include less green space than required","Residents strongly support new park construction in their neighborhoods"], correctIndex:0,
    explanation:"The critics' argument specifically depends on green space driving up nearby property values and displacing residents. If prices near new green space rise no faster than elsewhere, that specific mechanism is undercut. Reduced crime, compliance rates, and resident sentiment don't address the price/displacement link at all." },
  { id:"pr9", type:"reading", category:"reading", sub:"Reading Comprehension", passageId:"C",
    prompt:"The passage's description of the \"green gap\" most strongly implies that, absent policy intervention, access to green space would tend to:",
    options:["track existing patterns of neighborhood wealth rather than correct for them","disappear entirely from most American cities within a generation","become the single greatest driver of urban inequality","shift gradually from wealthy neighborhoods to lower-income ones"], correctIndex:0,
    explanation:"The passage describes green space as already concentrated in wealthier neighborhoods, with cities intervening specifically to change that pattern — implying that without intervention, the existing wealth-linked distribution simply continues." },
  { id:"pr10", type:"reading", category:"reading", sub:"Reading Comprehension", passageId:"C",
    prompt:"The passage's discussion of green gentrification primarily serves to:",
    options:["complicate what might otherwise seem like a straightforward policy fix for the green gap","refute the earlier claim that green space provides genuine public health benefits","demonstrate that the green gap described earlier does not actually exist","argue that cities should abandon green-space requirements altogether"], correctIndex:0,
    explanation:"The passage never walks back its earlier claims about green space's benefits or the reality of the green gap, and it never recommends abandoning the policy — it simply complicates the picture by noting an unintended consequence." }
];

/* =================== GRAMMAR & PUNCTUATION LESSON BANK =================== */
/* type: "error" (NO CHANGE style) or "blank" (choose the correct word) */
const GRAMMAR_BANK = [
  /* ---------------- LEVEL 1 — Foundations ---------------- */
  { id:"g1-1", level:1, type:"error", sub:"Pronoun Case",
    prompt:"The new intern already handles client calls more confidently than ⟦him⟧, even though she's been here only two weeks.",
    options:["NO CHANGE","his","himself","he"], correctIndex:3,
    explanation:"This is an elliptical comparison (\"than he [handles them]\"), so the pronoun takes the subjective case \"he,\" even though \"than him\" sounds natural in casual speech." },
  { id:"g1-2", level:1, type:"error", sub:"Dangling Modifiers",
    prompt:"⟦Its engine finally repaired⟧, the vintage car won three trophies at the summer show circuit.",
    options:["NO CHANGE","Repairing its engine","With its engine, repaired","Having repaired its engine"], correctIndex:0,
    explanation:"\"Its engine finally repaired\" is a nominative absolute with its own built-in subject (\"engine\") — it doesn't need to match \"the car\" and is already correct. \"Having repaired its engine\" wrongly implies the car repaired itself." },
  { id:"g1-3", level:1, type:"error", sub:"Subject-Verb Agreement",
    prompt:"Nearly sixty percent of the workforce ⟦was⟧ eligible for the new retirement plan, according to HR's internal audit.",
    options:["NO CHANGE","were","are","have been"], correctIndex:0,
    explanation:"With \"percent of,\" the verb agrees with the object of \"of\" — here the singular collective noun \"workforce.\" Compare \"sixty percent of the employees were eligible,\" where \"employees\" is plural." },
  { id:"g1-4", level:1, type:"error", sub:"Subjunctive Mood",
    prompt:"The lease stipulates that the tenant ⟦gives⟧ thirty days' written notice before vacating the property.",
    options:["NO CHANGE","gave","will give","give"], correctIndex:3,
    explanation:"After \"stipulates that,\" English requires the subjunctive base form \"give,\" not the third-person \"gives.\"" },
  { id:"g1-5", level:1, type:"error", sub:"That vs. Which",
    prompt:"The clause in the contract ⟦that⟧ limits liability to direct damages, rather than the one addressing arbitration, is what the plaintiff's attorneys are now challenging.",
    options:["NO CHANGE","which","who","whose"], correctIndex:0,
    explanation:"\"Rather than the one addressing arbitration\" shows this clause is being singled out from other possible clauses, making it restrictive — restrictive clauses take \"that,\" so the sentence is already correct." },
  { id:"g1-6", level:1, type:"error", sub:"Parallel Structure",
    prompt:"The audit found that the department had either misfiled the receipts or ⟦they were destroyed⟧ before the review began.",
    options:["NO CHANGE","destroys them","they had destroyed them","destroyed them"], correctIndex:3,
    explanation:"To match \"misfiled the receipts,\" the second branch needs the same past-tense-verb-plus-object structure, sharing \"had\": \"destroyed them.\" \"Destroys them\" breaks the parallel by shifting to present tense." },
  { id:"g1-7", level:1, type:"error", sub:"Word Usage",
    prompt:"The starting lineup ⟦is comprised of⟧ four returning veterans and one first-year player.",
    options:["NO CHANGE","is comprised by","comprises of","comprises"], correctIndex:3,
    explanation:"\"Comprise\" already means \"to consist of\" — the whole comprises its parts, with no \"of\" needed." },
  { id:"g1-8", level:1, type:"error", sub:"Faulty Predication",
    prompt:"The reason the flight was cancelled ⟦was because of⟧ a mechanical issue discovered during the pre-flight inspection.",
    options:["NO CHANGE","is because of","stemmed because of","was that"], correctIndex:3,
    explanation:"\"The reason...was because of\" is a redundant mixed construction. \"Stemmed because of\" is a tempting near-miss that half-fixes the wording but is still not idiomatic (\"stemmed from\" would work, not \"stemmed because of\")." },
  { id:"g1-9", level:1, type:"error", sub:"Clarity & Structure",
    prompt:"Under pressure to hit the deadline, ⟦the report she had asked to be finished quickly contained⟧ several typos, evidence of how rushed the final draft really was.",
    options:["NO CHANGE","the report she had quickly asked to be finished contained","the report she had asked to be finished, quickly, contained","the report she had asked to be quickly finished contained"], correctIndex:3,
    explanation:"As written, \"quickly\" sits ambiguously between \"asked\" and \"finished.\" Given the context of deadline pressure, it should describe how the report was finished, so it belongs directly next to \"finished.\"" },
  { id:"g1-10", level:1, type:"error", sub:"Pronoun Case",
    prompt:"When the votes were finally counted, it turned out to be ⟦him⟧ who had won the closest race in the district's history.",
    options:["NO CHANGE","his","himself","he"], correctIndex:3,
    explanation:"After the linking verb \"was/turned out to be,\" formal grammar calls for the subjective case \"he,\" even though \"it was him\" is common in casual speech." },
  { id:"g1-11", level:1, type:"error", sub:"Parallel Structure",
    prompt:"The team was both ⟦interested and excited about⟧ the new training facility.",
    options:["NO CHANGE","interested with and excited about","interested for and excited about","interested in and excited about"], correctIndex:3,
    explanation:"\"Interested\" and \"excited\" take different prepositions (\"interested in,\" \"excited about\") and can't share just one. \"Interested with\" and \"interested for\" are both wrong pairings — only \"interested in\" is correct." },
  { id:"g1-12", level:1, type:"error", sub:"That vs. Which",
    prompt:"The vaccine batch, ⟦that⟧ had been stored above the required temperature for several hours, was pulled from distribution as a precaution.",
    options:["NO CHANGE","who","whom","which"], correctIndex:3,
    explanation:"Set off by commas and adding extra information about an already-specific \"vaccine batch,\" this clause is nonrestrictive and needs \"which,\" not \"that.\"" },
  { id:"g1-13", level:1, type:"error", sub:"Sequence of Tense",
    prompt:"By the time inspectors arrived, the factory ⟦has already resumed⟧ operations, despite the standing order to remain closed.",
    options:["NO CHANGE","was already resuming","has already been resuming","had already resumed"], correctIndex:3,
    explanation:"\"By the time inspectors arrived\" sets up a past reference point, so the earlier action needs the past perfect: \"had already resumed.\"" },
  { id:"g1-14", level:1, type:"error", sub:"Pronoun Case",
    prompt:"The scholarship committee will interview ⟦whomever⟧ submits the strongest portfolio, regardless of GPA.",
    options:["NO CHANGE","who","which","whoever"], correctIndex:3,
    explanation:"The pronoun is the subject of \"submits,\" so it needs the subjective form \"whoever,\" despite following a verb that might tempt you toward the objective \"whomever.\"" },
  { id:"g1-15", level:1, type:"error", sub:"Faulty Comparison",
    prompt:"The city's population today is significantly larger than ⟦1950⟧.",
    options:["NO CHANGE","1950's","in the year of 1950","it was in 1950"], correctIndex:3,
    explanation:"As written, the sentence illogically compares \"population\" to \"1950\" (a year) rather than to the population in 1950. \"It was in 1950\" completes the comparison logically." },

  /* ---------------- LEVEL 2 — Developing ---------------- */
  { id:"g2-1", level:2, type:"error", sub:"Pronoun Case",
    prompt:"No one on the debate team prepares as thoroughly as ⟦her⟧, which is why she's been team captain for two years running.",
    options:["NO CHANGE","hers","herself","she"], correctIndex:3,
    explanation:"This elliptical comparison (\"as thoroughly as she [prepares]\") requires the subjective case \"she.\"" },
  { id:"g2-2", level:2, type:"error", sub:"Dangling Modifiers",
    prompt:"⟦After thoroughly reviewing the applicant's portfolio, the position was offered to her within a week.⟧",
    options:["NO CHANGE","Having thoroughly reviewed the applicant's portfolio, the position was offered to her within a week.","The position, after thoroughly reviewing the applicant's portfolio, was offered to her within a week.","After thoroughly reviewing the applicant's portfolio, the hiring committee offered her the position within a week."], correctIndex:3,
    explanation:"\"After thoroughly reviewing\" describes whoever did the reviewing, not \"the position\" — only naming \"the hiring committee\" as the subject fixes the dangling modifier. Simply swapping in \"Having\" leaves the same underlying error." },
  { id:"g2-3", level:2, type:"error", sub:"Subject-Verb Agreement",
    prompt:"None of the evidence presented at trial ⟦were⟧ sufficient to overturn the original verdict, according to the appellate panel.",
    options:["NO CHANGE","have been","are","was"], correctIndex:3,
    explanation:"\"Evidence\" is an uncountable mass noun, so \"none of the evidence\" takes the singular \"was,\" regardless of whether \"none\" can sometimes take a plural verb with countable nouns." },
  { id:"g2-4", level:2, type:"error", sub:"Subjunctive Mood",
    prompt:"Had the inspector ⟦checked⟧ the wiring more carefully, the fire might never have started.",
    options:["NO CHANGE","have checked","check","been checking"], correctIndex:0,
    explanation:"\"Had + subject + past participle\" is the correct inverted form for a past counterfactual — the sentence is already correct. \"Have checked\" is a common real error that redundantly doubles the past-counterfactual marking." },
  { id:"g2-5", level:2, type:"blank", sub:"Word Usage",
    prompt:"The witness's testimony was largely _____ with the physical evidence, though a few minor details didn't quite line up.",
    options:["consistent","complicit","complaisant","compliant"], correctIndex:0,
    explanation:"\"Consistent with\" means in agreement with. \"Compliant\" (obeying a rule or requirement) and \"complaisant\" (eager to please) are spelling-adjacent words with unrelated meanings that don't fit testimony matching evidence." },
  { id:"g2-6", level:2, type:"error", sub:"Faulty Predication",
    prompt:"⟦Inflation is when⟧ prices across the economy rise persistently over time, eroding purchasing power.",
    options:["NO CHANGE","is a situation when","is where","occurs when"], correctIndex:3,
    explanation:"\"Inflation\" is an economic process, not a time or place, so defining it with \"is when\" or \"is where\" illogically mismatches subject and predicate. \"Occurs when\" correctly links the process to the condition that produces it; \"is a situation when\" just as illogically pairs a noun with \"when.\"" },
  { id:"g2-7", level:2, type:"error", sub:"Clarity & Structure",
    prompt:"To encourage faster reporting, the company revised its policy so that ⟦employees who report safety violations promptly receive⟧ a confidential review of their complaint.",
    options:["NO CHANGE","employees, who report safety violations promptly, receive","employees who report safety violations receive promptly","employees who promptly report safety violations receive"], correctIndex:3,
    explanation:"As written, \"promptly\" could describe reporting or receiving. Given the stated goal of \"faster reporting,\" it should modify \"report,\" so it belongs directly before that verb." },
  { id:"g2-8", level:2, type:"error", sub:"Comma Usage",
    prompt:"The witness's account, ⟦corroborated by three surveillance videos and consistent with the forensic timeline established earlier⟧ ultimately persuaded the jury.",
    options:["NO CHANGE","...timeline established, earlier","...timeline, established earlier,","...timeline established earlier,"], correctIndex:3,
    explanation:"The nonrestrictive phrase opened with a comma after \"account,\" so it needs a matching closing comma before \"ultimately.\"" },
  { id:"g2-9", level:2, type:"error", sub:"Word Usage",
    prompt:"The task force ⟦will be comprised of⟧ representatives from each regional office once the reorganization is finalized.",
    options:["NO CHANGE","will comprise of","will be composed by","will comprise"], correctIndex:3,
    explanation:"\"Comprise\" already means \"to consist of\" — no preposition follows it. \"Will comprise of\" is a common hypercorrection that half-fixes the original error." },
  { id:"g2-10", level:2, type:"error", sub:"Sequence of Tense",
    prompt:"The witness testified that the defendant ⟦was⟧ at the scene twenty minutes before the fire started, contradicting the alibi given at trial.",
    options:["NO CHANGE","is","has been","had been"], correctIndex:3,
    explanation:"Being at the scene happened before the fire started, which itself is already in the past — this earlier-than-earlier relationship requires the past perfect \"had been.\"" },
  { id:"g2-11", level:2, type:"error", sub:"Word Usage",
    prompt:"The proposal was met with skepticism by investors who were wary of the startup's inexperienced leadership and ⟦suspicious about⟧ its unproven technology.",
    options:["NO CHANGE","suspiciously about","suspicious for","suspicious of"], correctIndex:3,
    explanation:"\"Suspicious of\" is the standard idiom, matching \"wary of\" in the same sentence." },
  { id:"g2-12", level:2, type:"error", sub:"Subject-Verb Agreement",
    prompt:"A total of forty-three complaints ⟦has been filed⟧ against the contractor since the project began.",
    options:["NO CHANGE","was filed","is filed","have been filed"], correctIndex:3,
    explanation:"\"A total of\" functions as a plural quantifier, similar to \"a number of,\" and takes a plural verb." },
  { id:"g2-13", level:2, type:"error", sub:"Dangling Modifiers",
    prompt:"⟦All expenses accounted for⟧, the wedding still cost significantly less than the couple had originally budgeted.",
    options:["NO CHANGE","Having accounted for all expenses","Accounting for all expenses","With all expenses, accounted for"], correctIndex:0,
    explanation:"\"All expenses accounted for\" is an absolute phrase with its own subject (\"expenses\") and doesn't need to match \"the wedding\" — it's already correct. Both \"Having accounted for all expenses\" and \"Accounting for all expenses\" wrongly imply the wedding itself did the accounting." },
  { id:"g2-14", level:2, type:"error", sub:"That vs. Which",
    prompt:"Policies ⟦which⟧ have not been reviewed within the past five years are automatically flagged for committee review.",
    options:["NO CHANGE","who","whose","that"], correctIndex:3,
    explanation:"This clause specifies which policies are meant — not all of them — making it restrictive, which calls for \"that\" rather than \"which.\"" },
  { id:"g2-15", level:2, type:"error", sub:"Faulty Comparison",
    prompt:"Unlike the previous CEO, whose priority was short-term profit, ⟦the new strategy emphasizes⟧ long-term sustainability.",
    options:["NO CHANGE","strategies now emphasize","the company now emphasizes strategies that","the new CEO's strategy emphasizes"], correctIndex:3,
    explanation:"As written, the sentence illogically compares \"the previous CEO\" to \"the new strategy.\" \"The new CEO's strategy\" restores a parallel comparison between the two leaders' approaches." },

  /* ---------------- LEVEL 3 — Proficient ---------------- */
  { id:"g3-1", level:3, type:"error", sub:"Clarity & Structure",
    prompt:"Some board members trust the CFO ⟦more than the COO⟧, a distinction that became clear only after the COO publicly questioned the CFO's numbers.",
    options:["NO CHANGE","more than trusting the COO","more than the COO does","more than they trust the COO"], correctIndex:3,
    explanation:"As written, the comparison is ambiguous between two readings. Given that the COO publicly doubted the CFO, the context supports comparing trust in the two people, which \"more than they trust the COO\" makes explicit." },
  { id:"g3-2", level:3, type:"blank", sub:"Word Usage",
    prompt:"Critics argued that the minister's position on the tariffs was no longer _____ once internal party documents contradicted his public statements.",
    options:["tenable","prudent","expedient","candid"], correctIndex:0,
    explanation:"\"Tenable\" means capable of being logically defended or maintained — exactly what's undermined when documents contradict a position. \"Prudent\" (wise) and \"candid\" (honest) describe unrelated qualities." },
  { id:"g3-3", level:3, type:"error", sub:"Semicolons & Colons",
    prompt:"The report's conclusion was unambiguous⟦, the pilot program having failed⟧ to reduce emergency room wait times in any of the four hospitals studied.",
    options:["NO CHANGE",", the pilot program, having failed,","; the pilot program having failed",": the pilot program had failed"], correctIndex:3,
    explanation:"\"The pilot program having failed\" is a participial phrase, not an independent clause, so a semicolon can't be used. A colon correctly introduces the explanation as its own complete statement." },
  { id:"g3-4", level:3, type:"error", sub:"Dangling Modifiers",
    prompt:"⟦Though originally skeptical of remote work, the pandemic forced the firm's leadership to reconsider its policies within weeks.⟧",
    options:["NO CHANGE","Originally skeptical of remote work, the firm's policies were reconsidered within weeks because of the pandemic.","The pandemic, though originally skeptical of remote work, forced the firm's leadership to reconsider its policies within weeks.","Though originally skeptical of remote work, the firm's leadership was forced by the pandemic to reconsider its policies within weeks."], correctIndex:3,
    explanation:"\"Though originally skeptical\" describes the people who held that view — the firm's leadership — not the pandemic or the policies themselves." },
  { id:"g3-5", level:3, type:"blank", sub:"Word Usage",
    prompt:"The senator's carefully hedged statement was widely seen as an attempt to _____ rather than directly answer the question.",
    options:["temporize","extemporize","acquiesce","capitulate"], correctIndex:0,
    explanation:"\"Temporize\" means to stall or act evasively to delay commitment — matching a hedged non-answer. \"Extemporize\" (to speak without preparation) is a near-identical-looking word with an unrelated meaning." },
  { id:"g3-6", level:3, type:"error", sub:"Apostrophes",
    prompt:"Six ⟦months⟧ notice is required before terminating the lease early.",
    options:["NO CHANGE","month's","months's","months'"], correctIndex:3,
    explanation:"This is a time-duration possessive, parallel to \"a day's work\": for the plural \"months,\" the apostrophe goes after the s — \"months'.\"" },
  { id:"g3-7", level:3, type:"error", sub:"Parallel Structure",
    prompt:"The whistleblower's testimony revealed not just that executives knew about the defect, but ⟦the coverup went all the way to the boardroom⟧.",
    options:["NO CHANGE","the coverup's reach extended to the boardroom","how the coverup went all the way to the boardroom","that the coverup went all the way to the boardroom"], correctIndex:3,
    explanation:"To match \"that executives knew,\" the second half needs its own \"that\"-clause: \"that the coverup went all the way to the boardroom.\"" },
  { id:"g3-8", level:3, type:"error", sub:"That vs. Which",
    prompt:"The engineers rejected every design ⟦which⟧ failed to meet the new safety threshold, resubmitting only the ones that passed.",
    options:["NO CHANGE","who","whom","that"], correctIndex:3,
    explanation:"\"Resubmitting only the ones that passed\" confirms not every design failed — this clause is restrictive, singling out which designs were rejected, so it needs \"that.\"" },
  { id:"g3-9", level:3, type:"blank", sub:"Word Usage",
    prompt:"The CEO's resignation letter was notably _____, offering no explanation beyond a single vague sentence about \"pursuing new opportunities.\"",
    options:["laconic","verbose","circumspect","equivocal"], correctIndex:0,
    explanation:"\"Laconic\" means using very few words. \"Circumspect\" (cautious of consequences) and \"equivocal\" (ambiguous) describe different qualities than sheer brevity." },
  { id:"g3-10", level:3, type:"error", sub:"Subjunctive Mood",
    prompt:"The committee insisted on an anonymous ballot, lest any member ⟦feels⟧ pressured to vote along factional lines.",
    options:["NO CHANGE","felt","will feel","feel"], correctIndex:3,
    explanation:"\"Lest,\" like \"so that...not,\" triggers the subjunctive base form \"feel,\" not the third-person \"feels.\"" },
  { id:"g3-11", level:3, type:"error", sub:"Semicolons & Colons",
    prompt:"The final report cited three contributing factors: outdated safety equipment, which had not been inspected in over a year⟦,⟧ insufficient staff training, particularly for new hires, and a systemic failure to report near-misses to corporate.",
    options:["NO CHANGE",":","(no punctuation)",";"], correctIndex:3,
    explanation:"Because the list items themselves contain commas, semicolons are needed to separate the three main items clearly." },
  { id:"g3-12", level:3, type:"error", sub:"Comparative Forms",
    prompt:"Given the budget constraints, the smaller venue was clearly the ⟦more preferable⟧ option for this year's gala.",
    options:["NO CHANGE","most preferable","very preferable","preferable"], correctIndex:3,
    explanation:"\"Preferable\" already means \"more desirable\" — pairing it with any degree modifier like \"more\" or \"very\" is redundant, and \"most preferable\" compounds the problem with a superlative." },
  { id:"g3-13", level:3, type:"blank", sub:"Word Usage",
    prompt:"The new regulations are designed to _____ greater transparency in how executive bonuses are calculated.",
    options:["effect","affect","affectation","effective"], correctIndex:0,
    explanation:"Here \"effect\" is used as a verb meaning \"to bring about\" — a less common but legitimate usage distinct from \"affect\" (to influence)." },
  { id:"g3-14", level:3, type:"error", sub:"Parallel Structure",
    prompt:"The policy applies to any employee who works more than thirty hours weekly, who receives employer-sponsored benefits, or who ⟦being with the company⟧ beyond one year.",
    options:["NO CHANGE","was with the company","is with the company","has been with the company"], correctIndex:3,
    explanation:"To match \"who works\" and \"who receives\" (present tense), the third clause needs a verb that correctly conveys accumulated duration up to now: \"has been with the company.\" \"Is with the company\" is present tense but doesn't capture that the one-year mark has already been reached." },
  { id:"g3-15", level:3, type:"error", sub:"Pronoun Case",
    prompt:"The award ultimately went to a researcher ⟦whom⟧ colleagues say has quietly mentored dozens of graduate students over three decades.",
    options:["NO CHANGE","whomever","whoever","who"], correctIndex:3,
    explanation:"The pronoun is the subject of \"has quietly mentored\"; \"colleagues say\" is a parenthetical insertion that doesn't change the case, so \"who\" is needed, not \"whom.\"" },

  /* ---------------- LEVEL 4 — Advanced ---------------- */
  { id:"g4-1", level:4, type:"error", sub:"Ambiguous Pronouns",
    prompt:"⟦After the board president briefed the treasurer, she recommended a full financial review.⟧",
    options:["NO CHANGE","She recommended a full financial review after the board president briefed the treasurer.","After the board president briefed the treasurer she recommended, a full financial review.","After the board president briefed the treasurer, the treasurer recommended a full financial review."], correctIndex:3,
    explanation:"\"She\" could refer to either the board president or the treasurer. Naming \"the treasurer\" directly removes the ambiguity; simply reordering the sentence, as the second option does, doesn't fix it." },
  { id:"g4-2", level:4, type:"blank", sub:"Word Usage",
    prompt:"The court's ruling _____ a precedent that had stood for nearly forty years.",
    options:["overturned","overruled","overrode","overthrew"], correctIndex:0,
    explanation:"\"Overturned a precedent\" is the standard legal collocation. \"Overruled\" typically applies to a specific objection or a lower court's decision within the same case; \"overthrew\" applies to governments, not legal precedent." },
  { id:"g4-3", level:4, type:"blank", sub:"Word Usage",
    prompt:"The lab's results are at odds _____ everything previously published on the subject.",
    options:["with","to","from","against"], correctIndex:0,
    explanation:"\"At odds with\" is the fixed idiom in formal English." },
  { id:"g4-4", level:4, type:"error", sub:"Concision",
    prompt:"The committee ⟦conducted an investigation into⟧ the allegations before reaching a decision.",
    options:["NO CHANGE","was conducting an investigation of","was investigating into","investigated"], correctIndex:3,
    explanation:"\"Conducted an investigation into\" buries the verb \"investigate\" inside a noun phrase. Using \"investigated\" directly is more concise and equally precise. \"Was conducting an investigation of\" fixes the preposition but keeps the same wordy, buried-verb problem." },
  { id:"g4-5", level:4, type:"blank", sub:"Word Usage",
    prompt:"The professor's feedback was _____ rather than constructive, leaving students unsure how to actually improve.",
    options:["carping","trenchant","didactic","candid"], correctIndex:0,
    explanation:"\"Carping\" means persistently and unfairly critical, or nitpicking — matching feedback that doesn't help students improve. \"Trenchant\" (sharp and incisive) actually leans positive, describing effective criticism, the opposite of what's needed here." },
  { id:"g4-6", level:4, type:"error", sub:"Comma Usage",
    prompt:"Her first novel ⟦the one that took her almost a decade to finish⟧ became an unexpected bestseller.",
    options:["NO CHANGE","the one that took her almost a decade to finish,","the one, that took her almost a decade to finish",", the one that took her almost a decade to finish,"], correctIndex:3,
    explanation:"The appositive needs a comma on both sides, opening after \"novel\" and closing before \"became.\" The other options supply only one comma, or put it in the wrong place." },
  { id:"g4-7", level:4, type:"error", sub:"Subjunctive Mood",
    prompt:"The statute mandates that any officer found in violation ⟦is⟧ immediately relieved of duty pending investigation.",
    options:["NO CHANGE","was","will be","be"], correctIndex:3,
    explanation:"After \"mandates that,\" the subjunctive base form \"be\" is required, not the indicative \"is.\"" },
  { id:"g4-8", level:4, type:"blank", sub:"Word Usage",
    prompt:"The whistleblower's account was later _____ by internal emails that surfaced during discovery.",
    options:["vindicated","vitiated","adjudicated","repudiated"], correctIndex:0,
    explanation:"\"Vindicated\" means shown to be right or justified. \"Vitiated\" (weakened, undermined) is a near-opposite that's easy to mistake for \"vindicated\" given the similar spelling." },
  { id:"g4-9", level:4, type:"error", sub:"Clarity & Structure",
    prompt:"Applicants who ⟦only submit their materials by the posted deadline⟧ will be considered for the fellowship.",
    options:["NO CHANGE","submit only their materials by the posted deadline","submit their materials, only, by the posted deadline","submit their materials only by the posted deadline"], correctIndex:3,
    explanation:"As written, \"only submit\" can suggest applicants merely submit (rather than do something more). Moving \"only\" next to \"by the posted deadline\" makes clear the limitation is about timing, not the act of submitting." },
  { id:"g4-10", level:4, type:"blank", sub:"Word Usage",
    prompt:"The ambassador's remarks were deliberately _____, allowing each side to interpret the statement as support for its position.",
    options:["equivocal","unequivocal","equitable","equanimous"], correctIndex:0,
    explanation:"\"Equivocal\" means deliberately open to more than one interpretation. \"Unequivocal\" is the direct opposite — clear and unambiguous — a sharp trap for a reader skimming past the prefix." },
  { id:"g4-11", level:4, type:"error", sub:"Parallel Structure",
    prompt:"The whitepaper argues that automation will eliminate certain jobs, that it will create others requiring different skills, and ⟦the overall effect on employment remains uncertain⟧.",
    options:["NO CHANGE","the overall effect on employment remaining uncertain","how the overall effect on employment remains uncertain","that the overall effect on employment remains uncertain"], correctIndex:3,
    explanation:"To match the first two \"that\"-clauses, the third item needs its own \"that\": \"that the overall effect...remains uncertain.\"" },
  { id:"g4-12", level:4, type:"blank", sub:"Word Usage",
    prompt:"The board's decision to delay the vote was widely seen as an attempt to _____ growing opposition rather than confront it directly.",
    options:["placate","capitulate","vacillate","obviate"], correctIndex:0,
    explanation:"\"Placate\" means to calm or appease. \"Capitulate\" (to surrender entirely) describes a much stronger, different response than merely calming opposition down." },
  { id:"g4-13", level:4, type:"blank", sub:"Word Usage",
    prompt:"The revised curriculum requires _____ writing assignments than the previous version, though each one now carries more weight toward the final grade.",
    options:["fewer","less","lesser","few"], correctIndex:0,
    explanation:"\"Assignments\" is a countable noun, so \"fewer\" is correct." },
  { id:"g4-14", level:4, type:"error", sub:"Comma Usage",
    prompt:"The company's headquarters in Austin⟦, which opened just last year,⟧ already employs more staff than the original location.",
    options:["NO CHANGE","which opened just last year","which opened just last year,",", which opened just last year"], correctIndex:0,
    explanation:"Since a company has only one headquarters in Austin, \"which opened just last year\" is nonessential, extra information and is already correctly set off with commas on both sides." },
  { id:"g4-15", level:4, type:"blank", sub:"Word Usage",
    prompt:"The two proposals are similar in scope but differ _____ in their funding mechanisms.",
    options:["markedly","marketable","marked","markingly"], correctIndex:0,
    explanation:"\"Markedly\" is the adverb form needed to modify the verb \"differ.\" \"Marked\" is an adjective and can't correctly modify a verb this way." },

  /* ---------------- LEVEL 5 — Expert ---------------- */
  { id:"g5-1", level:5, type:"error", sub:"Semicolons & Colons",
    prompt:"The audit uncovered inconsistent expense reporting across three departments⟦, consequently the CFO ordered⟧ a full review of reimbursement policies, procurement records, and vendor contracts.",
    options:["NO CHANGE",", and consequently, the CFO ordered","; consequently the CFO, ordered","; consequently, the CFO ordered"], correctIndex:3,
    explanation:"\"Consequently\" is a conjunctive adverb joining two independent clauses, so it needs a semicolon before it and a comma after it." },
  { id:"g5-2", level:5, type:"blank", sub:"Word Usage",
    prompt:"The philosopher's prose, though admired for its precision, was criticized by students as _____, requiring three or four readings to parse a single paragraph.",
    options:["abstruse","obtuse","astute","abstract"], correctIndex:0,
    explanation:"\"Abstruse\" means difficult to understand. \"Obtuse\" is a classic mix-up — it describes a person who is slow to understand, not a text that's hard to follow." },
  { id:"g5-3", level:5, type:"blank", sub:"Word Usage",
    prompt:"The treaty's language was intentionally _____, allowing each signatory nation to claim victory in its own domestic press.",
    options:["elastic","rigid","elusive","static"], correctIndex:0,
    explanation:"\"Elastic\" here means flexible enough to support more than one interpretation. \"Elusive\" (hard to pin down or define) is a spelling-adjacent word with a different meaning — it describes something hard to grasp, not something deliberately flexible." },
  { id:"g5-4", level:5, type:"blank", sub:"Word Usage",
    prompt:"A truly _____ historian resists the temptation to judge past figures by present-day standards.",
    options:["dispassionate","impassioned","compassionate","dispersed"], correctIndex:0,
    explanation:"\"Dispassionate\" means not influenced by emotion, objective. \"Impassioned\" (full of strong feeling) is nearly the opposite, despite the similar-looking prefix." },
  { id:"g5-5", level:5, type:"error", sub:"Subjunctive Mood",
    prompt:"If the committee ⟦would have reviewed⟧ the application more carefully last spring, the funding gap wouldn't still be a problem today.",
    options:["NO CHANGE","would review","has reviewed","had reviewed"], correctIndex:3,
    explanation:"This is a mixed conditional: a past hypothetical condition (\"had reviewed\") producing a present-tense result (\"wouldn't still be a problem today\"), which the sentence already states correctly." },
  { id:"g5-6", level:5, type:"error", sub:"Parallel Structure",
    prompt:"The reform would not merely adjust tax brackets but ⟦fundamentally it would restructure⟧ the entire system of deductions.",
    options:["NO CHANGE","it would fundamentally restructure","will fundamentally restructure","fundamentally restructure"], correctIndex:3,
    explanation:"To match the bare verb \"adjust,\" the second branch needs the same bare-verb form sharing \"would\": \"fundamentally restructure.\" \"Will fundamentally restructure\" breaks the parallel by switching to an inconsistent modal verb." },
  { id:"g5-7", level:5, type:"error", sub:"Pronoun Case",
    prompt:"The fellowship was awarded to the candidate ⟦whom⟧ the committee, notwithstanding two dissenting votes cast early in the deliberations, ultimately agreed had demonstrated the most rigorous research methodology.",
    options:["NO CHANGE","whomever","whoever","who"], correctIndex:3,
    explanation:"The pronoun is the subject of \"had demonstrated\"; the long parenthetical about dissenting votes doesn't change that it needs the subjective case \"who.\"" },
  { id:"g5-8", level:5, type:"blank", sub:"Word Usage",
    prompt:"The court's ruling set a _____ precedent, one that lower courts would cite for the next half-century.",
    options:["watershed","arbitrary","provisional","cursory"], correctIndex:0,
    explanation:"\"Watershed\" describes a critical turning point — matching a precedent cited for fifty years. \"Provisional\" (temporary) directly contradicts that lasting influence." },
  { id:"g5-9", level:5, type:"error", sub:"Formal Register",
    prompt:"The board's internal memo conceded that the merger's projected synergies were, frankly, ⟦a stretch⟧, given the two companies' incompatible supply chains.",
    options:["NO CHANGE","a long shot","questionable at best","overstated"], correctIndex:3,
    explanation:"\"Overstated\" precisely and formally names the problem. \"A long shot\" is a tempting near-miss, but it's just as colloquial as \"a stretch\" — it doesn't fix the register issue." },
  { id:"g5-10", level:5, type:"error", sub:"Comma Usage",
    prompt:"The plan, endorsed by the committee whose recommendation carries significant weight with the board⟦ has drawn criticism⟧ from several major stakeholders.",
    options:["NO CHANGE","; has drawn criticism","— has drawn criticism",", has drawn criticism"], correctIndex:3,
    explanation:"The nonrestrictive clause opened with a comma after \"plan,\" so it needs a matching closing comma before \"has.\"" },
  { id:"g5-11", level:5, type:"error", sub:"Semicolons & Colons",
    prompt:"The provision applies to three categories of claims: those filed within the statutory period, typically thirty days⟦,⟧ those filed late, but accompanied by a valid extension request, and those filed under subsection four, which covers exceptional circumstances.",
    options:["NO CHANGE",":","(no punctuation)",";"], correctIndex:3,
    explanation:"Because each item in this list already contains an internal comma, semicolons are needed to keep the three categories clearly separated." },
  { id:"g5-12", level:5, type:"error", sub:"Pronoun Case",
    prompt:"No board member has raised more objections during deliberations than ⟦him⟧, whose skepticism, according to colleagues, stems from having witnessed two prior mergers collapse.",
    options:["NO CHANGE","his","himself","he"], correctIndex:3,
    explanation:"This elliptical comparison (\"than he [has raised]\") requires the subjective case \"he.\"" },
  { id:"g5-13", level:5, type:"blank", sub:"Word Usage",
    prompt:"Though the treaty's language sounds _____ today, it was genuinely controversial when first proposed.",
    options:["anodyne","platitudinous","vitriolic","hackneyed"], correctIndex:0,
    explanation:"\"Anodyne\" means inoffensive and unlikely to provoke controversy — fitting language that no longer sounds contentious. \"Vitriolic\" (harsh, bitter) is nearly the opposite." },
  { id:"g5-14", level:5, type:"error", sub:"Dangling Modifiers",
    prompt:"⟦Having weighed the competing expert testimonies for nearly a week, a verdict was finally reached by the jury on the eighth day of deliberation.⟧",
    options:["NO CHANGE","The jury's verdict, after having weighed the competing expert testimonies for nearly a week, was finally reached on the eighth day of deliberation.","A verdict, having weighed the competing expert testimonies for nearly a week, was finally reached by the jury on the eighth day of deliberation.","Having weighed the competing expert testimonies for nearly a week, the jury finally reached a verdict on the eighth day of deliberation."], correctIndex:3,
    explanation:"\"Having weighed\" describes the jury, not \"a verdict\" or \"the jury's verdict\" — only naming \"the jury\" as the very next subject fixes the dangling modifier; the possessive in the second option doesn't count as that subject." },
  { id:"g5-15", level:5, type:"blank", sub:"Word Usage",
    prompt:"The proposal received endorsements from no _____ than twelve former ambassadors, a remarkable show of bipartisan support.",
    options:["fewer","less","lesser","few"], correctIndex:0,
    explanation:"\"Ambassadors\" is countable, so \"no fewer than twelve\" is correct — contrast with an uncountable amount, as in \"no less than $12,000.\"" }
];
