/* ---------------------------------------------------------------
   Bloom — content bank
   Placement test (40 Qs) + leveled Grammar & Punctuation lessons
----------------------------------------------------------------*/

const LEVEL_NAMES = {
  1: "Foundations",
  2: "Developing",
  3: "Proficient",
  4: "Advanced",
  5: "Expert"
};

const LEVEL_BLURB = {
  1: "You're building the essential rules — subject-verb agreement, apostrophes, and clear sentences.",
  2: "You're sharpening the everyday tricky spots — commas, semicolons, and word mix-ups.",
  3: "You're refining nuance — who/whom, subjunctive mood, and precise punctuation.",
  4: "You're polishing advanced style — idiom, concision, and formal register.",
  5: "You're mastering expert-level nuance — diction, layered punctuation, and elegant structure."
};

const CATEGORY_NAMES = {
  error: "Grammar & Sentence Errors",
  blank: "Word Choice",
  vocab: "Vocabulary",
  reading: "Reading Comprehension"
};

/* =================== PLACEMENT TEST (40 questions) =================== */
const PLACEMENT_QUESTIONS = [
  // ---- Error identification (12) ----
  { id:"pe1", type:"error", category:"error", sub:"Subject-Verb Agreement",
    prompt:"The board of directors, several of whom have served for over a decade, ⟦remain⟧ divided on the proposed merger.",
    options:["NO CHANGE","remains","have remained","was remaining"], correctIndex:1,
    explanation:"The true subject is the singular collective noun \"board,\" not \"several\" or \"directors\" from the intervening phrase, so it takes \"remains.\" \"Have remained\" wrongly agrees with the nearby plural \"several\" — a very common mistake when a modifying phrase sits between subject and verb." },
  { id:"pe2", type:"error", category:"error", sub:"Subjunctive Mood",
    prompt:"If the merger ⟦would have gone⟧ through as planned, thousands of jobs would have been saved.",
    options:["NO CHANGE","had gone","would go","was going"], correctIndex:1,
    explanation:"The \"if\" clause of a counterfactual takes the past perfect (\"had gone\"), not a second \"would have.\" Doubling up \"would have...would have\" is one of the most common errors in conditional sentences." },
  { id:"pe3", type:"error", category:"error", sub:"Pronoun Case",
    prompt:"⟦Whomever⟧ finishes the race first will receive the trophy.",
    options:["NO CHANGE","Whoever","Who","Which"], correctIndex:1,
    explanation:"The pronoun is the subject of \"finishes,\" so it needs the subjective form \"whoever.\" People often reach for \"whomever\" because it sounds more formal — a classic hypercorrection." },
  { id:"pe4", type:"error", category:"error", sub:"Subjunctive Mood",
    prompt:"The professor insisted that every student ⟦submit⟧ the assignment electronically, regardless of previous instructions.",
    options:["NO CHANGE","submits","submitted","will submit"], correctIndex:0,
    explanation:"After a mandative verb like \"insisted that,\" English requires the subjunctive base form \"submit,\" not \"submits.\" The sentence is already correct — the common mistake is \"fixing\" it to agree with \"student.\"" },
  { id:"pe5", type:"error", category:"error", sub:"Parallel Structure",
    prompt:"The report recommends not only increasing the training budget but also ⟦that managers should attend⟧ quarterly workshops.",
    options:["NO CHANGE","attending","to attend","managers attending"], correctIndex:1,
    explanation:"\"Not only...but also\" needs matching forms: the gerund \"increasing\" pairs with the gerund \"attending.\" \"To attend\" and \"managers attending\" are both common ways writers break parallel structure without noticing." },
  { id:"pe6", type:"error", category:"error", sub:"Apostrophes",
    prompt:"The committee reviewed the proposal and found ⟦it's⟧ underlying assumptions questionable, particularly regarding projected revenue.",
    options:["NO CHANGE","their","it is","its"], correctIndex:3,
    explanation:"The possessive \"its\" belongs before \"underlying assumptions.\" \"It's\" always means \"it is\"; \"their\" is a common substitution people reach for when unsure of \"its,\" even though \"proposal\" is singular." },
  { id:"pe7", type:"error", category:"error", sub:"Comparative Forms",
    prompt:"Critics argue that the sequel's plot is not as compelling ⟦than⟧ the original.",
    options:["NO CHANGE","like","that","as"], correctIndex:3,
    explanation:"\"As...as\" comparisons need \"as\" on both sides, not \"than.\" This error comes from blending two correct constructions — \"not as X as Y\" and \"less X than Y\" — into one incorrect hybrid." },
  { id:"pe8", type:"error", category:"error", sub:"Parallel Structure",
    prompt:"The workshop will teach participants how to manage conflict effectively, communicate under pressure, and ⟦building⟧ consensus among diverse teams.",
    options:["NO CHANGE","to build","builds","build"], correctIndex:3,
    explanation:"After \"how to,\" all three verbs share that \"to\": manage, communicate, and build. \"Building\" breaks the parallel bare-infinitive form — one of the most common errors in long lists." },
  { id:"pe9", type:"error", category:"error", sub:"Word Usage",
    prompt:"The CEO's remarks were widely interpreted as a tacit admission ⟦of⟧ the company's declining market share.",
    options:["NO CHANGE","about","for","with"], correctIndex:0,
    explanation:"\"Admission of\" is the standard idiom. \"About,\" \"for,\" and \"with\" are the kinds of prepositions writers substitute by analogy with similar phrases (\"comment about,\" \"excuse for\"), but none fit \"admission.\"" },
  { id:"pe10", type:"error", category:"error", sub:"That vs. Which",
    prompt:"Economists point to the housing shortage, ⟦that⟧ has driven prices up nearly forty percent since 2020, as the primary cause of the affordability crisis.",
    options:["NO CHANGE","who","which","whose"], correctIndex:2,
    explanation:"The clause is set off by commas and simply adds extra information about \"the housing shortage,\" so it's nonrestrictive and needs \"which,\" not \"that.\"" },
  { id:"pe11", type:"error", category:"error", sub:"Subject-Verb Agreement",
    prompt:"A number of studies ⟦has shown⟧ that remote work increases short-term productivity but may erode long-term collaboration.",
    options:["NO CHANGE","having shown","have shown","was shown"], correctIndex:2,
    explanation:"\"A number of\" functions as a plural quantifier (roughly \"many\") and takes a plural verb — the reverse of \"the number of,\" which is singular. This is one of the most widely confused agreement rules in English." },
  { id:"pe12", type:"error", category:"error", sub:"Misplaced Modifiers",
    prompt:"Researchers ⟦only found⟧ three viable candidates for the vaccine trial after screening thousands of compounds.",
    options:["NO CHANGE","found only","found, only","only, found"], correctIndex:1,
    explanation:"As written, \"only found\" can suggest the researchers merely found (rather than invented) the candidates. Placing \"only\" next to \"three viable candidates\" — the thing it actually limits — removes the ambiguity. Misplacing \"only\" is one of the most common real-world modifier errors." },

  // ---- Fill in the blank (10) ----
  { id:"pb1", type:"blank", category:"blank", sub:"Word Usage",
    prompt:"Many investors remained _____ to risk even after the market rebounded, preferring safe bonds over volatile stocks.",
    options:["averse","adverse","adversarial","diverse"], correctIndex:0,
    explanation:"\"Averse\" describes a person's strong dislike or reluctance toward something. \"Adverse\" (unfavorable) describes conditions, not attitudes — \"adverse to risk\" is one of the most common mix-ups in English." },
  { id:"pb2", type:"blank", category:"blank", sub:"Word Usage",
    prompt:"To meet the deadline, the team agreed to _____ their usual code review process, a decision they later regretted.",
    options:["forgo","forego","forgot","forbid"], correctIndex:0,
    explanation:"\"Forgo\" means to do without something. \"Forego\" (with the extra \"e\") means to go before, as in \"the foregoing chapter\" — a classic spelling-based mix-up." },
  { id:"pb3", type:"blank", category:"blank", sub:"Word Usage",
    prompt:"The keynote address will _____ the panel discussion, so arrive early if you don't want to miss it.",
    options:["precede","proceed","succeed","supersede"], correctIndex:0,
    explanation:"\"Precede\" means to come before. \"Succeed\" (to come after) is the near-opposite and a very tempting mix-up; \"proceed\" (to continue) is a sound-alike error." },
  { id:"pb4", type:"blank", category:"blank", sub:"Word Usage",
    prompt:"Investigators found her account entirely _____, corroborated by three independent witnesses.",
    options:["credible","credulous","creditable","incredulous"], correctIndex:0,
    explanation:"\"Credible\" means believable. \"Credulous\" describes a person too ready to believe things — a common mix-up, since both come from the same root but describe opposite roles (the believer vs. the thing believed)." },
  { id:"pb5", type:"blank", category:"blank", sub:"Word Usage",
    prompt:"After years of market dominance, the company grew _____, ignoring emerging competitors until it was too late.",
    options:["complacent","complaisant","compliant","competent"], correctIndex:0,
    explanation:"\"Complacent\" means self-satisfied and unaware of danger. \"Complaisant\" (eager to please) is a near-identical spelling with a very different meaning — a genuinely common mix-up." },
  { id:"pb6", type:"blank", category:"blank", sub:"Word Usage",
    prompt:"After the turbulent flight, she felt _____ and had to sit down immediately.",
    options:["nauseated","nauseous","nauseating","noxious"], correctIndex:0,
    explanation:"Strictly, \"nauseated\" describes the feeling of sickness, while \"nauseous\" describes something that causes sickness (\"a nauseous smell\"). Using \"nauseous\" to mean \"feeling sick\" is one of the most common — and most frequently corrected — mix-ups in formal English." },
  { id:"pb7", type:"blank", category:"blank", sub:"Word Usage",
    prompt:"The negotiations followed a _____ path, full of last-minute reversals and complicated side deals, before finally reaching a deal.",
    options:["tortuous","torturous","tenuous","onerous"], correctIndex:0,
    explanation:"\"Tortuous\" means winding and full of twists. \"Torturous\" (extremely painful) differs by a single letter and is one of the most common near-homophone mix-ups in English." },
  { id:"pb8", type:"blank", category:"blank", sub:"Word Usage",
    prompt:"The mayor's _____ acceptance of bribes from developers eventually led to his indictment.",
    options:["venal","venial","vernal","venerable"], correctIndex:0,
    explanation:"\"Venal\" means corruptible, willing to act dishonestly for money. \"Venial\" (a minor, forgivable fault) looks nearly identical but means almost the opposite — a genuine and very common confusion." },
  { id:"pb9", type:"blank", category:"blank", sub:"Word Usage",
    prompt:"The professor's _____ prose, dense with jargon and needlessly long sentences, made the article almost unreadable.",
    options:["turgid","turbid","terse","tepid"], correctIndex:0,
    explanation:"\"Turgid\" describes writing that is pompous and overblown. \"Turbid\" describes murky, cloudy liquid — a classic spelling-based mix-up with an unrelated meaning." },
  { id:"pb10", type:"blank", category:"blank", sub:"Word Usage",
    prompt:"After three failed business partnerships, she grew _____ of signing any new contracts without her lawyer's review.",
    options:["wary","weary","dreary","wiry"], correctIndex:0,
    explanation:"\"Wary\" means cautious of danger. \"Weary\" (tired) is a near-identical spelling and one of the most frequently confused word pairs in everyday writing." },

  // ---- Vocabulary in context (8) ----
  { id:"pv1", type:"vocab", category:"vocab", sub:"Vocabulary",
    prompt:"Critics dismissed the senator's fulsome praise of his own achievements as transparent self-promotion. As used here, \"fulsome\" most nearly means:",
    options:["excessive and insincere","abundant and generous","brief and understated","well-deserved and modest"], correctIndex:0,
    explanation:"\"Fulsome\" means excessive to the point of being insincere or distasteful. Many people mistakenly think it simply means \"abundant\" or \"generous\" — one of the most commonly misused words in English." },
  { id:"pv2", type:"vocab", category:"vocab", sub:"Vocabulary",
    prompt:"The oppressive heat and humidity of the jungle enervated the expedition team within days. As used here, \"enervated\" most nearly means:",
    options:["drained of energy","energized and invigorated","frightened and unnerved","angered and irritated"], correctIndex:0,
    explanation:"\"Enervate\" means to weaken or drain of energy — despite sounding like \"energize,\" it means almost the opposite. This false-friend pair trips up even strong readers." },
  { id:"pv3", type:"vocab", category:"vocab", sub:"Vocabulary",
    prompt:"Only after visiting the site did she grasp the full enormity of what had happened there. As used here, \"enormity\" most nearly means:",
    options:["extreme wickedness","extremely large size","great sadness","historical importance"], correctIndex:0,
    explanation:"Traditionally, \"enormity\" refers to great wickedness or monstrousness, not mere large size — a distinction that's increasingly blurred in casual use but is still tested in formal writing." },
  { id:"pv4", type:"vocab", category:"vocab", sub:"Vocabulary",
    prompt:"Rather than laughing at the absurd proposal, the board members simply looked bemused, unsure how to respond. As used here, \"bemused\" most nearly means:",
    options:["confused and puzzled","amused and entertained","angry and offended","bored and indifferent"], correctIndex:0,
    explanation:"\"Bemused\" means puzzled or bewildered. It's often mistaken for \"amused\" because the words look and sound alike — but they describe unrelated reactions." },
  { id:"pv5", type:"vocab", category:"vocab", sub:"Vocabulary",
    prompt:"A noisome odor rose from the stagnant canal, forcing residents to keep their windows shut. As used here, \"noisome\" most nearly means:",
    options:["foul-smelling","extremely loud","poisonous","damp and cold"], correctIndex:0,
    explanation:"\"Noisome\" means offensive, especially to the sense of smell — it has nothing to do with \"noisy,\" despite the resemblance." },
  { id:"pv6", type:"vocab", category:"vocab", sub:"Vocabulary",
    prompt:"Despite the company's mounting losses, the CEO remained surprisingly sanguine about its prospects for recovery. As used here, \"sanguine\" most nearly means:",
    options:["optimistic and confident","violent and bloodthirsty","gloomy and pessimistic","indifferent and unconcerned"], correctIndex:0,
    explanation:"\"Sanguine\" means cheerfully optimistic. Its resemblance to \"sanguinary\" (bloody) leads many people to guess the wrong, more violent meaning." },
  { id:"pv7", type:"vocab", category:"vocab", sub:"Vocabulary",
    prompt:"Her assiduous note-taking throughout the trial later proved invaluable when the case went to appeal. As used here, \"assiduous\" most nearly means:",
    options:["diligent and careful","bold and daring","difficult and exhausting","casual and infrequent"], correctIndex:0,
    explanation:"\"Assiduous\" means showing great care and persistent effort. It's frequently confused with the similar-sounding \"audacious\" (bold) or \"arduous\" (difficult)." },
  { id:"pv8", type:"vocab", category:"vocab", sub:"Vocabulary",
    prompt:"The lawyer's specious argument sounded convincing at first, but it fell apart under closer examination. As used here, \"specious\" most nearly means:",
    options:["seemingly plausible but wrong","spacious and open","special and unique","clearly correct and well-supported"], correctIndex:0,
    explanation:"\"Specious\" describes something that appears true or reasonable but is actually false. Its resemblance to \"spacious\" and \"special\" causes frequent mix-ups." },

  // ---- Reading comprehension (10, across 3 shared passages) ----
  { id:"pr1", type:"reading", category:"reading", sub:"Reading Comprehension", passageId:"A",
    passage:"Over the past decade, researchers replicating landmark psychology studies have succeeded barely half the time, a pattern known as the reproducibility crisis. Some blame small sample sizes and selective reporting, where striking results get published while null findings go unseen. Others locate the problem deeper, in incentives that reward novelty over rigor. Whatever the cause, the result is the same: a body of accepted knowledge riddled with findings that may not hold up. Some journals now require researchers to register hypotheses before collecting data, curbing the temptation to reshape conclusions after seeing results.",
    prompt:"According to the passage, \"selective reporting\" contributes to the reproducibility crisis because it:",
    options:["allows striking results to be published while null results go unseen, distorting the evidence","causes researchers to intentionally falsify their data","leads journals to reject all psychology studies","increases the number of studies published each year"], correctIndex:0,
    explanation:"The passage says striking results \"reach publication while null findings languish unseen.\" It never claims researchers falsify data — that's a common overreach that conflates publication bias with outright fraud." },
  { id:"pr2", type:"reading", category:"reading", sub:"Reading Comprehension", passageId:"A",
    prompt:"The passage implies that pre-registering hypotheses is intended to prevent researchers from:",
    options:["adjusting their stated conclusions to fit whatever results they find","collecting enough data to reach statistical significance","collaborating with other researchers on a single study","publishing their findings in more than one journal"], correctIndex:0,
    explanation:"The passage says the practice curbs \"the temptation to reshape a study's conclusions after seeing its results\" — the other options aren't supported by the text." },
  { id:"pr3", type:"reading", category:"reading", sub:"Reading Comprehension", passageId:"A",
    prompt:"The passage's overall treatment of the reproducibility crisis is best described as:",
    options:["measured — treating the problem as real while acknowledging debate over its cause","dismissive — suggesting critics have overstated the crisis","alarmist — predicting the collapse of psychology as a field","resigned — implying no meaningful response is possible"], correctIndex:0,
    explanation:"The passage presents competing explanations without dismissing the problem, and it closes by describing an actual response (pre-registration) — hardly the stance of a resigned or dismissive author." },

  { id:"pr4", type:"reading", category:"reading", sub:"Reading Comprehension", passageId:"B",
    passage:"Every morning of my childhood began the same way: a walk along a gravel road past my grandfather's orchard. In autumn, the apples hung so heavy the branches bent toward the ground, and I'd pick one without slowing, biting into it before I'd gone another ten steps. My grandfather always waved from the porch, though I rarely saw him leave it. Only years later, returning to find the orchard sold and the road paved over, did I understand how much of my sense of home had rested on those small, repeated moments rather than on any single place.",
    prompt:"The passage suggests that the narrator's understanding of \"home\" is best described as:",
    options:["a feeling built from ordinary, repeated experiences rather than a fixed place","something she could only appreciate once it was gone, and never before","primarily defined by her relationship with her grandfather specifically","a place she deliberately avoided returning to as an adult"], correctIndex:0,
    explanation:"The final sentence attributes her sense of home to \"small, repeated moments,\" not to any single place or person. The passage never claims she couldn't appreciate it earlier — only that she \"understood\" it later, a subtler claim." },
  { id:"pr5", type:"reading", category:"reading", sub:"Reading Comprehension", passageId:"B",
    prompt:"The detail that the narrator bit into the apple \"without slowing\" primarily suggests:",
    options:["how habitual and unremarkable the action was to her","that she was in a hurry to reach school on time","that she worried about being caught taking the apple","that she didn't especially like the taste of the apples"], correctIndex:0,
    explanation:"Nothing in the passage mentions urgency, guilt, or dislike — the detail simply conveys how routine and automatic the gesture had become, fitting the passage's larger point about small repeated moments." },
  { id:"pr6", type:"reading", category:"reading", sub:"Reading Comprehension", passageId:"B",
    prompt:"The final sentence's list of details (\"the crunch of gravel...\") functions primarily to:",
    options:["give concrete examples of the small moments that built her sense of home","prove that the narrator's childhood memories are unreliable","contrast with unhappier memories described earlier in the passage","explain the narrator's own decision to sell the orchard"], correctIndex:0,
    explanation:"These details illustrate the \"small, repeated moments\" the sentence just referenced. The passage never suggests unhappy memories to contrast with, and it says the orchard \"was sold\" without saying by whom." },

  { id:"pr7", type:"reading", category:"reading", sub:"Reading Comprehension", passageId:"C",
    passage:"Urban planners increasingly treat green space — parks, tree-lined streets, community gardens — as more than an amenity. Studies link it to lower rates of stress-related illness, cleaner air, and even reduced crime. Yet the benefit is unevenly distributed: wealthier neighborhoods tend to have expansive parks and mature tree canopies, while lower-income areas often make do with vacant lots and little shade — a disparity sometimes called the 'green gap.' Several cities have responded by requiring new developments to include public green space regardless of income. Critics counter that such requirements raise nearby property values and can hasten the displacement of longtime residents, a pattern known as green gentrification.",
    prompt:"According to the passage, green space has been linked to all of the following EXCEPT:",
    options:["increased local tax revenue for city governments","lower rates of stress-related illness","cleaner air","reduced crime"], correctIndex:0,
    explanation:"The passage names stress-related illness, air quality, and crime — tax revenue is never mentioned." },
  { id:"pr8", type:"reading", category:"reading", sub:"Reading Comprehension", passageId:"C",
    prompt:"As used in the passage, the \"green gap\" refers specifically to:",
    options:["the unequal access to green space between wealthier and lower-income neighborhoods","the difference between a city's current parks and its planned future parks","the drop in tree cover caused by new construction projects","the disagreement between critics and planners over development rules"], correctIndex:0,
    explanation:"The term is defined in the sentence immediately before it, describing the gap between neighborhoods with abundant green space and those without." },
  { id:"pr9", type:"reading", category:"reading", sub:"Reading Comprehension", passageId:"C",
    prompt:"The passage suggests that green gentrification is problematic mainly because it:",
    options:["can undercut the goal of green-space policies by pricing out the residents they were meant to help","makes new parks more expensive for cities to build and maintain","reduces the total number of new parks built each year","shows that lower-income neighborhoods don't actually want more green space"], correctIndex:0,
    explanation:"The passage links green gentrification to rising property values and the displacement of \"longtime residents\" — the very residents the green-space policies were meant to benefit. Nothing is said about construction costs, park quantity, or residents' desires." },
  { id:"pr10", type:"reading", category:"reading", sub:"Reading Comprehension", passageId:"C",
    prompt:"The primary purpose of the passage is to:",
    options:["describe a benefit of green space, show it's unequally distributed, and complicate a common policy response","argue that cities should stop building parks in wealthy neighborhoods","prove that green space has no measurable effect on public health","recommend a specific solution to the problem of green gentrification"], correctIndex:0,
    explanation:"The passage moves from benefit, to inequity, to the complications of a proposed fix — but unlike Passage A, it never actually proposes or recommends a solution to that final complication." }
];

/* =================== GRAMMAR & PUNCTUATION LESSON BANK =================== */
/* type: "error" (NO CHANGE style) or "blank" (choose the correct word) */
const GRAMMAR_BANK = [
  /* ---------------- LEVEL 1 — Foundations ---------------- */
  { id:"g1-1", level:1, type:"error", sub:"Subject-Verb Agreement",
    prompt:"Each of the applicants ⟦were⟧ asked to submit a writing sample along with their résumé.",
    options:["NO CHANGE","was","are","have been"], correctIndex:1,
    explanation:"\"Each\" is singular, so it takes the singular verb \"was,\" even though \"applicants\" is plural." },
  { id:"g1-2", level:1, type:"error", sub:"Apostrophes",
    prompt:"The airline lost three ⟦passengers'⟧ luggage during the layover, prompting dozens of complaints.",
    options:["NO CHANGE","passenger's","passengers's","passenger"], correctIndex:0,
    explanation:"\"Passengers'\" is already the correct plural possessive for three passengers. \"Passenger's\" would wrongly imply only one passenger lost luggage." },
  { id:"g1-3", level:1, type:"error", sub:"Comma Usage",
    prompt:"⟦Although the restaurant was fully booked the host managed to find us a table near the kitchen.⟧",
    options:["NO CHANGE","Although the restaurant was fully booked, the host managed to find us a table near the kitchen.","Although the restaurant, was fully booked the host managed to find us a table near the kitchen.","Although the restaurant was fully booked the host, managed to find us a table near the kitchen."], correctIndex:1,
    explanation:"A comma follows an introductory clause (\"Although...booked\") to separate it from the main clause." },
  { id:"g1-4", level:1, type:"error", sub:"Run-ons & Fragments",
    prompt:"⟦The flight was delayed for six hours, most passengers spent the time browsing the airport's overpriced shops.⟧",
    options:["NO CHANGE","The flight was delayed for six hours; most passengers spent the time browsing the airport's overpriced shops.","The flight was delayed for six hours most passengers spent the time browsing the airport's overpriced shops.","The flight was delayed for six hours, and, most passengers spent the time browsing the airport's overpriced shops."], correctIndex:1,
    explanation:"Two independent clauses can't be joined by just a comma. A semicolon correctly links these closely related ideas." },
  { id:"g1-5", level:1, type:"error", sub:"Capitalization",
    prompt:"The documentary examines how the ⟦industrial revolution⟧ transformed daily life across the continent.",
    options:["NO CHANGE","Industrial Revolution","Industrial revolution","industrial Revolution"], correctIndex:1,
    explanation:"\"Industrial Revolution\" names a specific historical era and is a proper noun, so both words are capitalized." },
  { id:"g1-6", level:1, type:"error", sub:"Pronoun Case",
    prompt:"The recruiter offered the position to Maya and ⟦I⟧, though we hadn't even finished the interview process.",
    options:["NO CHANGE","me","myself","us"], correctIndex:1,
    explanation:"The pronoun is the object of \"offered...to,\" so it needs the objective case \"me.\" \"Myself\" is a common overcorrection people reach for when they're unsure whether \"I\" or \"me\" is right." },
  { id:"g1-7", level:1, type:"blank", sub:"Word Usage",
    prompt:"Before signing, read the contract and all of _____ terms and conditions carefully.",
    options:["its","it's","their","it"], correctIndex:0,
    explanation:"\"Its\" is the possessive form needed before \"terms and conditions.\" \"It's\" always means \"it is\"; \"their\" wrongly treats the singular \"contract\" as plural." },
  { id:"g1-8", level:1, type:"error", sub:"End Punctuation",
    prompt:"The manager asked whether the shipment had arrived yet⟦.⟧",
    options:["NO CHANGE","?","!",","], correctIndex:0,
    explanation:"This is an indirect question (\"asked whether...\"), not a directly quoted one, so it correctly ends with a period. A common mistake is adding a question mark here." },
  { id:"g1-9", level:1, type:"error", sub:"Subject-Verb Agreement",
    prompt:"A stack of unpaid invoices ⟦sit⟧ on the accountant's desk, untouched since the audit began.",
    options:["NO CHANGE","sits","are sitting","were sitting"], correctIndex:1,
    explanation:"The subject is the singular \"stack,\" not the plural \"invoices\" in the prepositional phrase, so the verb should be \"sits.\"" },
  { id:"g1-10", level:1, type:"error", sub:"Apostrophes",
    prompt:"By the ⟦1980's⟧, the neighborhood had changed almost beyond recognition.",
    options:["NO CHANGE","1980s","1980s'","1980,s"], correctIndex:1,
    explanation:"Decades are made plural without an apostrophe: \"1980s.\"" },
  { id:"g1-11", level:1, type:"error", sub:"Comma Usage",
    prompt:"The new hire, eager to make a good impression⟦ arrived⟧ a full hour before her scheduled start time.",
    options:["NO CHANGE",", arrived","arrived,",", arrived,"], correctIndex:1,
    explanation:"The nonessential phrase \"eager to make a good impression\" opened with a comma after \"hire,\" so it needs a matching closing comma before \"arrived.\"" },
  { id:"g1-12", level:1, type:"blank", sub:"Word Usage",
    prompt:"_____ never been to Portugal, so we spent hours researching restaurants before the trip.",
    options:["We'd","Wed","We'll","Were"], correctIndex:0,
    explanation:"\"We'd\" is the contraction for \"we had,\" needed for the past-perfect \"had never been.\"" },
  { id:"g1-13", level:1, type:"error", sub:"Run-ons & Fragments",
    prompt:"⟦Even though the budget had already been approved by the board.⟧",
    options:["NO CHANGE","Even though the budget had already been approved by the board, the project stalled for months.","The budget had already been approved even though by the board.","Even though, the budget had already been approved by the board."], correctIndex:1,
    explanation:"\"Even though...board\" is a subordinate clause with no independent clause attached — it's a fragment until a main clause completes the thought." },
  { id:"g1-14", level:1, type:"error", sub:"Pronoun Agreement",
    prompt:"If a customer wants a refund, ⟦he⟧ must bring the original receipt within thirty days.",
    options:["NO CHANGE","they","it","one"], correctIndex:1,
    explanation:"Since \"a customer\" could be any gender, the inclusive, widely accepted singular \"they\" is the better choice than the generic \"he.\"" },
  { id:"g1-15", level:1, type:"blank", sub:"Word Usage",
    prompt:"The warranty covers manufacturing defects, but not damage caused by normal _____ and tear.",
    options:["wear","were","where","we're"], correctIndex:0,
    explanation:"\"Wear and tear\" is the idiom; the other options are homophones that don't fit." },

  /* ---------------- LEVEL 2 — Developing ---------------- */
  { id:"g2-1", level:2, type:"error", sub:"Comma Usage",
    prompt:"My colleague Priya⟦ who transferred from the Chicago office⟧ will be leading the onboarding session.",
    options:["NO CHANGE",", who transferred from the Chicago office,",", who transferred from the Chicago office","who transferred from the Chicago office,"], correctIndex:1,
    explanation:"Because \"Priya\" already uniquely identifies her, \"who transferred from the Chicago office\" is extra, nonessential information and needs commas on both sides." },
  { id:"g2-2", level:2, type:"blank", sub:"Word Usage",
    prompt:"Chronic sleep deprivation can _____ memory, mood, and even long-term cardiovascular health.",
    options:["affect","effect","affects","effected"], correctIndex:0,
    explanation:"\"Affect\" is the verb meaning \"to influence.\" \"Effect\" is usually the noun (a result)." },
  { id:"g2-3", level:2, type:"error", sub:"Apostrophes",
    prompt:"The startup's board voted to overhaul ⟦it's⟧ entire compensation structure after the resignations.",
    options:["NO CHANGE","their","it is","its"], correctIndex:3,
    explanation:"The possessive \"its\" is needed here. \"It's\" always means \"it is,\" and \"their\" wrongly treats the singular \"startup\" as plural." },
  { id:"g2-4", level:2, type:"error", sub:"Subject-Verb Agreement",
    prompt:"Either the interns or the project manager ⟦is⟧ responsible for updating the shared calendar each week.",
    options:["NO CHANGE","are","were","have been"], correctIndex:0,
    explanation:"With \"either...or,\" the verb agrees with the nearer subject — the singular \"project manager\" — so \"is\" is already correct, even though the plural \"interns\" appears first." },
  { id:"g2-5", level:2, type:"error", sub:"Pronoun Agreement",
    prompt:"The nonprofit relies on volunteers to run ⟦their⟧ annual fundraising gala.",
    options:["NO CHANGE","its","his or her","one's"], correctIndex:1,
    explanation:"\"Nonprofit\" is a singular noun, so it should be referred to with the singular \"its,\" not \"their.\"" },
  { id:"g2-6", level:2, type:"error", sub:"Semicolons & Colons",
    prompt:"Ticket sales exceeded expectations, ⟦therefore the theater⟧ extended the show's run by two weeks.",
    options:["NO CHANGE",", therefore, the theater","; therefore, the theater","therefore, the theater"], correctIndex:2,
    explanation:"When \"therefore\" joins two independent clauses, it needs a semicolon before it and a comma after it." },
  { id:"g2-7", level:2, type:"blank", sub:"Word Usage",
    prompt:"The renovation ended up costing far more _____ the contractor originally estimated.",
    options:["than","then","that","them"], correctIndex:0,
    explanation:"\"Than\" is used for comparisons; \"then\" refers to time or sequence." },
  { id:"g2-8", level:2, type:"error", sub:"Misplaced Modifiers",
    prompt:"⟦Rummaging through old boxes in the attic, a box of childhood photographs surprised her.⟧",
    options:["NO CHANGE","Rummaging through old boxes in the attic, she was surprised to find a box of childhood photographs.","A box of childhood photographs, rummaging through old boxes in the attic, surprised her.","She was surprised, rummaging through old boxes in the attic, to find a box of childhood photographs."], correctIndex:1,
    explanation:"The opening phrase describes who was rummaging, so the subject right after the comma must be \"she,\" not the box of photographs itself." },
  { id:"g2-9", level:2, type:"error", sub:"Parallel Structure",
    prompt:"The internship offers hands-on training, mentorship from senior staff, and ⟦you get to network⟧ with industry leaders.",
    options:["NO CHANGE","networking","the chance to network","to network"], correctIndex:1,
    explanation:"To match the nouns \"training\" and \"mentorship,\" the third item should also be a noun: \"networking.\"" },
  { id:"g2-10", level:2, type:"error", sub:"Comma Usage",
    prompt:"Employees⟦ who falsify their expense reports⟧ will face immediate termination.",
    options:["NO CHANGE",", who falsify their expense reports,",", who falsify their expense reports","who falsify their expense reports,"], correctIndex:0,
    explanation:"This clause specifies which employees are meant — not all of them — so it's a restrictive clause and correctly takes no commas." },
  { id:"g2-11", level:2, type:"error", sub:"Subject-Verb Agreement",
    prompt:"Statistics, as an academic discipline, ⟦are⟧ often misunderstood by people who haven't studied it.",
    options:["NO CHANGE","is","were","has been"], correctIndex:1,
    explanation:"When \"statistics\" refers to the field of study itself, it's treated as singular — \"is,\" not \"are.\"" },
  { id:"g2-12", level:2, type:"blank", sub:"Word Usage",
    prompt:"After the scandal, the board moved quickly to _____ new oversight procedures.",
    options:["institute","instigate","institution","instate"], correctIndex:0,
    explanation:"\"Institute\" means to establish or set up. \"Instigate\" means to provoke or stir up (usually something negative) — a genuine mix-up given the similar spelling." },
  { id:"g2-13", level:2, type:"error", sub:"Apostrophes",
    prompt:"Fashion in the ⟦1920's⟧ was defined by looser silhouettes and shorter hemlines.",
    options:["NO CHANGE","1920s","1920s'","the 1920,s"], correctIndex:1,
    explanation:"Decades are made plural without an apostrophe: \"1920s.\"" },
  { id:"g2-14", level:2, type:"error", sub:"Parallel Structure",
    prompt:"The revised proposal is more concise, better organized, and ⟦has more persuasiveness⟧ than the original draft.",
    options:["NO CHANGE","more persuasive","persuasively better","has persuasiveness"], correctIndex:1,
    explanation:"To match the adjective phrases \"more concise\" and \"better organized,\" the third item should also be an adjective phrase: \"more persuasive.\"" },
  { id:"g2-15", level:2, type:"error", sub:"Run-ons & Fragments",
    prompt:"⟦The vendor missed the delivery deadline again, we had no choice but to find a new supplier.⟧",
    options:["NO CHANGE","The vendor missed the delivery deadline again, so we had no choice but to find a new supplier.","The vendor missed the delivery deadline again we had no choice but to find a new supplier.","The vendor missed the delivery deadline again, and, we had no choice but to find a new supplier."], correctIndex:1,
    explanation:"A comma alone can't join two independent clauses. Adding \"so\" after the comma fixes the splice and shows the cause-and-effect relationship." },

  /* ---------------- LEVEL 3 — Proficient ---------------- */
  { id:"g3-1", level:3, type:"error", sub:"Pronoun Case",
    prompt:"The foundation awards grants to researchers ⟦who⟧ it believes will have the greatest impact on public health.",
    options:["NO CHANGE","whom","whoever","whomever"], correctIndex:0,
    explanation:"The pronoun is the subject of \"will have\"; \"it believes\" is a parenthetical insertion that doesn't change the case. \"Who\" is already correct, though \"whom\" tempts readers who assume the word right after a preposition-like structure must be objective." },
  { id:"g3-2", level:3, type:"blank", sub:"Word Usage",
    prompt:"The revised policy applies to households earning _____ than sixty thousand dollars annually.",
    options:["less","fewer","lesser","few"], correctIndex:0,
    explanation:"A dollar amount is treated as a single quantity, not a set of countable units, so \"less\" is correct, even though \"dollars\" looks countable." },
  { id:"g3-3", level:3, type:"error", sub:"Semicolons & Colons",
    prompt:"After months of deliberation, the jury reached a verdict⟦, that the defendant was guilty on all counts⟧.",
    options:["NO CHANGE",": the defendant was guilty on all counts.","; the defendant was guilty on all counts.","— that the defendant was guilty on all counts"], correctIndex:1,
    explanation:"A colon introduces an explanation after a complete independent clause — here, what the verdict actually was." },
  { id:"g3-4", level:3, type:"error", sub:"Dangling Modifiers",
    prompt:"⟦Exhausted after the twelve-hour shift, the thought of cooking dinner felt unbearable.⟧",
    options:["NO CHANGE","Exhausted after the twelve-hour shift, she found the thought of cooking dinner unbearable.","The thought of cooking dinner, exhausted after the twelve-hour shift, felt unbearable.","Cooking dinner felt unbearable, exhausted after the twelve-hour shift."], correctIndex:1,
    explanation:"\"Exhausted\" describes the person, not \"the thought,\" so \"she\" must be the subject right after the comma." },
  { id:"g3-5", level:3, type:"blank", sub:"Word Usage",
    prompt:"The CFO's carefully worded statement seemed to _____, without saying outright, that layoffs were imminent.",
    options:["imply","infer","implying","inferred"], correctIndex:0,
    explanation:"\"Imply\" is what a speaker or piece of writing does — hint at something. \"Infer\" is what a listener does when drawing a conclusion." },
  { id:"g3-6", level:3, type:"error", sub:"Apostrophes",
    prompt:"⟦Anna and Ben's⟧ apartments are on opposite ends of the same building.",
    options:["NO CHANGE","Anna's and Ben's","Anna's and Bens","Annas and Ben's"], correctIndex:1,
    explanation:"Because Anna and Ben own separate apartments, each name needs its own possessive marker. Only shared, joint ownership takes a single possessive on the last name." },
  { id:"g3-7", level:3, type:"error", sub:"Parallel Structure",
    prompt:"The senator's plan would neither reduce the deficit nor ⟦creating⟧ the jobs it promises.",
    options:["NO CHANGE","create","created","creation"], correctIndex:1,
    explanation:"\"Neither...nor\" needs matching verb forms: the base form \"reduce\" pairs with the base form \"create.\"" },
  { id:"g3-8", level:3, type:"error", sub:"That vs. Which",
    prompt:"The only strategy ⟦which⟧ consistently improved test scores involved smaller class sizes.",
    options:["NO CHANGE","that","who","whom"], correctIndex:1,
    explanation:"This clause identifies which specific strategy is meant, making it restrictive — and restrictive clauses take \"that,\" not \"which,\" in careful formal usage." },
  { id:"g3-9", level:3, type:"blank", sub:"Word Usage",
    prompt:"The nearest hospital was ten miles _____ than the clinic we'd originally planned to visit.",
    options:["farther","further","far","farthest"], correctIndex:0,
    explanation:"\"Farther\" refers to literal physical distance (\"ten miles\"), while \"further\" is reserved for figurative or abstract extent." },
  { id:"g3-10", level:3, type:"error", sub:"Subjunctive Mood",
    prompt:"The bylaws require that every board member ⟦discloses⟧ potential conflicts of interest before each vote.",
    options:["NO CHANGE","disclose","disclosed","will disclose"], correctIndex:1,
    explanation:"After \"require that,\" English uses the subjunctive base form \"disclose,\" not the third-person \"discloses.\"" },
  { id:"g3-11", level:3, type:"error", sub:"Semicolons & Colons",
    prompt:"The grant committee evaluates three factors: ⟦the project's feasibility, budget, and timeline, the applicant's track record, funding history, and institutional support, and the potential for long-term community impact⟧.",
    options:["NO CHANGE","the project's feasibility, budget, and timeline; the applicant's track record, funding history, and institutional support; and the potential for long-term community impact","the project's feasibility, budget and timeline, the applicant's track record; funding history and institutional support; and the potential for long-term community impact","the project's feasibility; budget, and timeline, the applicant's track record, funding history and institutional support, and the potential; for long-term community impact"], correctIndex:1,
    explanation:"When list items already contain commas, semicolons separate the three main groups so a reader can tell where each one ends." },
  { id:"g3-12", level:3, type:"error", sub:"Comparative Forms",
    prompt:"Among the three finalists, the panel judged her proposal to be the ⟦more⟧ innovative.",
    options:["NO CHANGE","most","much more","very most"], correctIndex:1,
    explanation:"Comparing three or more things requires the superlative \"most,\" not the comparative \"more,\" which is reserved for comparing exactly two." },
  { id:"g3-13", level:3, type:"blank", sub:"Word Usage",
    prompt:"The new CEO moved quickly to _____ sweeping changes across every department.",
    options:["effect","affect","effective","affecting"], correctIndex:0,
    explanation:"Here \"effect\" is used as a verb meaning \"to bring about\" (as in \"effect changes\") — a less common but legitimate usage distinct from \"affect\" (to influence)." },
  { id:"g3-14", level:3, type:"error", sub:"Parallel Structure",
    prompt:"The memo explains why the merger makes financial sense, how it will affect staffing, and ⟦what is the timeline for implementation⟧.",
    options:["NO CHANGE","what the timeline for implementation is","the implementation timeline","when implementation will begin"], correctIndex:1,
    explanation:"Embedded questions use statement word order, not question word order — \"what the timeline is,\" matching \"why the merger makes\" and \"how it will affect.\"" },
  { id:"g3-15", level:3, type:"error", sub:"Pronoun Case",
    prompt:"The prize will go to ⟦whoever⟧ the judges determine wrote the most original entry.",
    options:["NO CHANGE","whomever","who","which"], correctIndex:0,
    explanation:"The pronoun is the subject of \"wrote\" (\"whoever...wrote the most original entry\"); \"the judges determine\" is a parenthetical insertion that doesn't change the case." },

  /* ---------------- LEVEL 4 — Advanced ---------------- */
  { id:"g4-1", level:4, type:"error", sub:"Ambiguous Pronouns",
    prompt:"⟦When the auditor met with the CFO, she raised concerns about several unexplained transactions.⟧",
    options:["NO CHANGE","When the auditor met with the CFO, the auditor raised concerns about several unexplained transactions.","When the auditor met with the CFO she raised concerns, about several unexplained transactions.","She raised concerns about several unexplained transactions when the auditor met with the CFO."], correctIndex:1,
    explanation:"\"She\" could refer to either the auditor or the CFO. Naming \"the auditor\" directly removes the ambiguity." },
  { id:"g4-2", level:4, type:"blank", sub:"Word Usage",
    prompt:"The senator's speech was carefully crafted to _____ responsibility for the crisis onto his predecessor.",
    options:["deflect","obviate","mitigate","abrogate"], correctIndex:0,
    explanation:"\"Deflect responsibility onto\" is the natural idiom. \"Obviate\" (make unnecessary), \"mitigate\" (lessen severity), and \"abrogate\" (formally repeal) are all plausible-sounding but don't fit this meaning." },
  { id:"g4-3", level:4, type:"blank", sub:"Word Usage",
    prompt:"The findings are largely consistent _____ earlier studies, though the sample size here is much smaller.",
    options:["with","to","from","of"], correctIndex:0,
    explanation:"\"Consistent with\" is the standard idiom in formal English." },
  { id:"g4-4", level:4, type:"error", sub:"Concision",
    prompt:"⟦Due to the fact that⟧ the flight was delayed, we missed our connection.",
    options:["NO CHANGE","Because","Given the fact that","Owing to the fact of"], correctIndex:1,
    explanation:"\"Due to the fact that\" is a wordy substitute for \"because.\" All three wrong options recycle the same padded \"fact that\" construction." },
  { id:"g4-5", level:4, type:"blank", sub:"Word Usage",
    prompt:"Despite _____ interruptions from the construction next door, the meeting eventually covered every agenda item.",
    options:["continual","continuous","consecutive","contiguous"], correctIndex:0,
    explanation:"\"Continual\" describes something repeated, starting and stopping — exactly what \"interruptions\" are. \"Continuous\" means unbroken, which would actually contradict the idea of separate interruptions." },
  { id:"g4-6", level:4, type:"error", sub:"Comma Usage",
    prompt:"The firm's newest partner, ⟦a former federal prosecutor⟧ brings twenty years of litigation experience to the team.",
    options:["NO CHANGE","a former federal prosecutor,","a former federal prosecutor","a former federal prosecutor —"], correctIndex:1,
    explanation:"The appositive \"a former federal prosecutor\" opened with a comma after \"partner,\" so it needs a matching closing comma before \"brings.\"" },
  { id:"g4-7", level:4, type:"error", sub:"Subjunctive Mood",
    prompt:"The physician recommended that the patient ⟦avoid⟧ strenuous activity for at least six weeks.",
    options:["NO CHANGE","avoids","avoided","will avoid"], correctIndex:0,
    explanation:"After \"recommended that,\" the subjunctive base form \"avoid\" is already correct — a common mistake is \"fixing\" it to agree with \"the patient.\"" },
  { id:"g4-8", level:4, type:"blank", sub:"Word Usage",
    prompt:"Investigators uncovered an _____ scheme to funnel campaign donations through shell companies.",
    options:["illicit","elicit","illicitly","elicited"], correctIndex:0,
    explanation:"\"Illicit\" means illegal or forbidden. \"Elicit\" (to draw out) is an unrelated word with a similar sound." },
  { id:"g4-9", level:4, type:"error", sub:"Clarity & Structure",
    prompt:"To speed up the certification process, the training team announced that ⟦employees who complete the training quickly will receive certification⟧.",
    options:["NO CHANGE","employees who quickly complete the training will receive certification.","employees, who complete the training quickly, will receive certification.","employees who complete the training will quickly receive certification."], correctIndex:1,
    explanation:"As written, \"quickly\" could describe either finishing the training fast or receiving certification fast. Given the context of speeding up certification, the intended meaning is that employees finish quickly — moving \"quickly\" next to \"complete\" removes the ambiguity." },
  { id:"g4-10", level:4, type:"blank", sub:"Word Usage",
    prompt:"With the corporate takeover _____, employees scrambled to update their résumés.",
    options:["imminent","eminent","immanent","prominent"], correctIndex:0,
    explanation:"\"Imminent\" means about to happen. \"Eminent\" (distinguished) is a common sound-alike mix-up." },
  { id:"g4-11", level:4, type:"error", sub:"Parallel Structure",
    prompt:"The grant requires applicants to describe their research goals, to outline a realistic budget, and ⟦demonstrating⟧ institutional support.",
    options:["NO CHANGE","to demonstrate","demonstrate","that demonstrates"], correctIndex:1,
    explanation:"To match \"to describe\" and \"to outline,\" the third item needs the same infinitive form: \"to demonstrate.\"" },
  { id:"g4-12", level:4, type:"blank", sub:"Word Usage",
    prompt:"The results of the pilot program are directly _____ to the increased funding it received.",
    options:["attributable","attributed","contributory","accredited"], correctIndex:0,
    explanation:"\"Attributable to\" is the standard adjective-plus-preposition idiom. \"Contributory\" reverses the logic (it would mean the results caused the funding, not the reverse), and \"accredited\" means officially certified — an unrelated meaning." },
  { id:"g4-13", level:4, type:"blank", sub:"Word Usage",
    prompt:"The company reduced the _____ of paperwork required for reimbursement requests.",
    options:["amount","number","quantity","count"], correctIndex:0,
    explanation:"\"Paperwork\" is an uncountable mass noun, so \"amount\" is standard. \"Number\" is reserved for countable nouns — a very common mix-up." },
  { id:"g4-14", level:4, type:"error", sub:"Comma Usage",
    prompt:"⟦Contractors, who fail to submit invoices by the fifteenth, will not be paid⟧ until the following cycle.",
    options:["NO CHANGE","Contractors who fail to submit invoices by the fifteenth will not be paid","Contractors, who fail to submit invoices by the fifteenth will not be paid","Contractors who fail to submit invoices by the fifteenth, will not be paid"], correctIndex:1,
    explanation:"\"Who fail to submit invoices by the fifteenth\" specifies which contractors are meant, making it restrictive. As written, the commas wrongly imply all contractors miss the deadline." },
  { id:"g4-15", level:4, type:"blank", sub:"Word Usage",
    prompt:"The spokesperson tried to _____ investors that the company's finances remained sound.",
    options:["assure","ensure","insure","advise"], correctIndex:0,
    explanation:"\"Assure\" means to tell someone confidently in order to dispel doubt. \"Ensure\" means to make certain of a thing or outcome, not a person's feelings." },

  /* ---------------- LEVEL 5 — Expert ---------------- */
  { id:"g5-1", level:5, type:"error", sub:"Semicolons & Colons",
    prompt:"The panel reached its decision⟦;⟧ awarding the contract to the lowest bidder.",
    options:["NO CHANGE",":",",","(no punctuation)"], correctIndex:1,
    explanation:"A semicolon requires an independent clause on both sides, but \"awarding the contract...\" is only a phrase. A colon correctly introduces this explanatory phrase after the complete clause \"the panel reached its decision.\"" },
  { id:"g5-2", level:5, type:"blank", sub:"Word Usage",
    prompt:"The therapist handled the sensitive disclosure with such _____ that the client never felt judged.",
    options:["discretion","discreteness","discrepancy","discord"], correctIndex:0,
    explanation:"\"Discretion\" (tact, careful judgment) is the noun form of \"discreet.\" \"Discreteness\" (separateness) is the noun form of the unrelated word \"discrete\" — a classic confusable pair." },
  { id:"g5-3", level:5, type:"blank", sub:"Word Usage",
    prompt:"By continuing to operate without a permit, the company openly _____ local zoning laws.",
    options:["flouted","flaunted","floated","founded"], correctIndex:0,
    explanation:"\"Flout\" means to openly disregard a rule. \"Flaunt\" (to show off) is a frequently confused near-homophone." },
  { id:"g5-4", level:5, type:"blank", sub:"Word Usage",
    prompt:"A good mediator must remain _____ in the dispute's outcome, even while caring deeply about reaching a fair resolution.",
    options:["disinterested","uninterested","interested","biased"], correctIndex:0,
    explanation:"\"Disinterested\" means impartial — contrasted here with \"caring deeply,\" which rules out \"uninterested\" (not caring at all), the word it's most often confused with." },
  { id:"g5-5", level:5, type:"error", sub:"Subjunctive Mood",
    prompt:"⟦If the merger was⟧ approved by regulators, the combined company would control nearly forty percent of the market.",
    options:["NO CHANGE","If the merger were","If the merger is","If the merger would be"], correctIndex:1,
    explanation:"This hypothetical, not-yet-decided scenario requires the subjunctive \"were,\" not \"was.\"" },
  { id:"g5-6", level:5, type:"error", sub:"Parallel Structure",
    prompt:"The initiative aims not only to reduce emissions across the supply chain but also ⟦at improving⟧ working conditions for factory employees.",
    options:["NO CHANGE","to improve","improving","improve"], correctIndex:1,
    explanation:"\"Not only...but also\" needs matching forms: the infinitive \"to reduce\" pairs with the infinitive \"to improve.\"" },
  { id:"g5-7", level:5, type:"error", sub:"Pronoun Case",
    prompt:"The award will go to ⟦whomever⟧ the panel, after extensive deliberation and several rounds of debate, ultimately deems most deserving.",
    options:["NO CHANGE","whoever","who","which"], correctIndex:0,
    explanation:"The pronoun is the object of \"deems\" (\"the panel deems whomever...most deserving\"); the long parenthetical about deliberation doesn't change its objective role. \"Whomever\" is already correct." },
  { id:"g5-8", level:5, type:"blank", sub:"Word Usage",
    prompt:"The treaty signing was a _____ moment, marking the first peace agreement between the two nations in decades.",
    options:["historic","historical","historically","history's"], correctIndex:0,
    explanation:"\"Historic\" means significant in history. \"Historical\" merely means relating to history or the past in general — a distinction often blurred in casual writing." },
  { id:"g5-9", level:5, type:"error", sub:"Formal Register",
    prompt:"The quarterly report noted that revenue had ⟦kind of⟧ plateaued after years of steady growth.",
    options:["NO CHANGE","largely","definitely","very much"], correctIndex:1,
    explanation:"\"Kind of\" is too colloquial for a formal report. \"Largely\" conveys the intended degree without the informal hedge; \"definitely\" wrongly shifts the meaning to certainty rather than extent." },
  { id:"g5-10", level:5, type:"error", sub:"Comma Usage",
    prompt:"The CEO, whose annual bonus depends on quarterly earnings targets⟦ has consistently opposed⟧ any policy that might slow short-term growth.",
    options:["NO CHANGE",", has consistently opposed","; has consistently opposed","— has consistently opposed"], correctIndex:1,
    explanation:"The nonrestrictive clause \"whose annual bonus...targets\" opened with a comma after \"CEO,\" so it needs a matching closing comma before \"has.\"" },
  { id:"g5-11", level:5, type:"error", sub:"Semicolons & Colons",
    prompt:"The merger agreement outlines several conditions⟦, a joint board of directors, shared intellectual property rights, and a five-year non-compete clause, all subject to regulatory approval⟧.",
    options:["NO CHANGE",": a joint board of directors, shared intellectual property rights, and a five-year non-compete clause, all subject to regulatory approval","; a joint board of directors, shared intellectual property rights, and a five-year non-compete clause, all subject to regulatory approval","a joint board of directors; shared intellectual property rights; and a five-year non-compete clause; all subject to regulatory approval"], correctIndex:1,
    explanation:"A colon introduces the list after the complete independent clause \"the merger agreement outlines several conditions.\"" },
  { id:"g5-12", level:5, type:"error", sub:"Pronoun Case",
    prompt:"The committee ultimately chose a candidate ⟦who⟧, despite reservations from two senior members, the majority felt was best qualified.",
    options:["NO CHANGE","whom","whoever","whomever"], correctIndex:0,
    explanation:"The pronoun is the subject of \"was best qualified\"; \"despite reservations...\" and \"the majority felt\" are parenthetical structures that don't change its subjective role. \"Who\" is already correct." },
  { id:"g5-13", level:5, type:"blank", sub:"Word Usage",
    prompt:"Though relatively unknown outside academic circles, the professor was _____ among specialists in medieval trade routes.",
    options:["eminent","imminent","immanent","ambient"], correctIndex:0,
    explanation:"\"Eminent\" means distinguished or well-known within a field. \"Imminent\" (about to happen) and \"immanent\" (inherent within) are common sound-alike mix-ups." },
  { id:"g5-14", level:5, type:"error", sub:"Dangling Modifiers",
    prompt:"⟦After reviewing thousands of applications, the position was ultimately offered to an internal candidate.⟧",
    options:["NO CHANGE","After reviewing thousands of applications, the hiring committee ultimately offered the position to an internal candidate.","The position, after reviewing thousands of applications, was ultimately offered to an internal candidate.","Thousands of applications were reviewed, and the position was ultimately offered to an internal candidate, after reviewing."], correctIndex:1,
    explanation:"\"After reviewing thousands of applications\" describes the hiring committee, not \"the position,\" so \"the hiring committee\" must be the subject right after the comma." },
  { id:"g5-15", level:5, type:"blank", sub:"Word Usage",
    prompt:"The new software requires _____ steps to complete the same task, saving employees significant time.",
    options:["fewer","less","lesser","few"], correctIndex:0,
    explanation:"\"Steps\" is a countable noun, so \"fewer\" is correct — the counterpart to the rule that uncountable quantities take \"less.\"" }
];
